(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function auth(){return window.CAPTAUP_AUTH}
function isCeo(){const u=window.__captaupUser;return u&&(['ceo','administrador'].includes(String(u.accessRole||'').toLowerCase()))}
function css(){if($('adm-access-css'))return;const s=document.createElement('style');s.id='adm-access-css';s.textContent=`
#captaupAdmBtn{border:1px solid #25597b;background:#0b2130;color:#86cfff;border-radius:999px;padding:7px 10px;font-size:8px;font-weight:950;cursor:pointer}.adm-badge{display:inline-grid;place-items:center;min-width:16px;height:16px;padding:0 4px;border-radius:999px;background:#ff6b6b;color:white;font-size:7px;margin-left:4px}.adm-overlay{position:fixed;inset:0;z-index:100002;background:#02070dea;display:grid;place-items:center;padding:16px}.adm-box{width:min(650px,100%);max-height:88vh;overflow:auto;background:#07131f;border:1px solid #23577a;border-radius:20px;padding:18px;color:#eaf7ff;box-shadow:0 24px 80px #000b}.adm-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.adm-title{font-size:19px;font-weight:950}.adm-sub{font-size:9px;color:#7f9bb0;margin-top:3px}.adm-close{border:0;border-radius:8px;background:#102536;color:#a9cbe0;padding:8px 10px;font-size:8px;font-weight:900;cursor:pointer}.adm-list{display:grid;gap:9px;margin-top:14px}.adm-item{border:1px solid #1a3c55;border-radius:12px;background:#081823;padding:11px}.adm-item b{display:block;font-size:11px;word-break:break-all}.adm-item small{display:block;color:#7692a6;font-size:8px;margin-top:3px}.adm-actions{display:flex;gap:8px;margin-top:9px}.adm-ok,.adm-no{border:0;border-radius:8px;padding:8px 10px;color:white;font-size:8px;font-weight:950;cursor:pointer}.adm-ok{background:#1dbd73}.adm-no{background:#a63b45}.adm-empty{padding:20px;text-align:center;color:#7894a8;font-size:9px}.adm-section{margin-top:18px}.adm-section-title{font-size:10px;font-weight:950;color:#9bc9e8;letter-spacing:.5px}
`;document.head.appendChild(s)}
function data(){const a=auth();if(!a)return null;return{a,req:a.read(a.requestsKey,[]),users:a.read(a.usersKey,{})}}
function approve(id){const d=data();if(!d)return;const r=d.req.find(x=>String(x.id)===String(id));if(!r)return;r.status='approved';r.resolvedAt=new Date().toISOString();d.a.write(d.a.requestsKey,d.req);d.users[r.email]={email:r.email,name:r.email.split('@')[0].replace(/[._-]+/g,' ').toUpperCase(),accessRole:'Profissional',performanceRole:'promotor',active:true,approved:true};d.a.write(d.a.usersKey,d.users);render();updateBadge()}
function reject(id){const d=data();if(!d)return;const r=d.req.find(x=>String(x.id)===String(id));if(!r)return;r.status='rejected';r.resolvedAt=new Date().toISOString();d.a.write(d.a.requestsKey,d.req);render();updateBadge()}
function render(){const root=$('captaupAdmPanel');if(!root)return;const d=data();if(!d)return;const pending=d.req.filter(r=>r.status==='pending');const approved=Object.values(d.users).filter(u=>u.approved&&u.active);root.innerHTML=`<div class="adm-box"><div class="adm-head"><div><div class="adm-title">ADM • Acessos</div><div class="adm-sub">Somente você aprova quem entra no CAPTAUP.</div></div><button class="adm-close" id="admClose">FECHAR</button></div><div class="adm-section"><div class="adm-section-title">SOLICITAÇÕES PENDENTES (${pending.length})</div><div class="adm-list">${pending.length?pending.map(r=>`<div class="adm-item"><b>${esc(r.email)}</b><small>${new Date(r.requestedAt).toLocaleString('pt-BR')}</small><div class="adm-actions"><button class="adm-ok" data-ok="${r.id}">APROVAR</button><button class="adm-no" data-no="${r.id}">RECUSAR</button></div></div>`).join(''):'<div class="adm-empty">Nenhum pedido pendente.</div>'}</div></div><div class="adm-section"><div class="adm-section-title">E-MAILS APROVADOS (${approved.length})</div><div class="adm-list">${approved.map(u=>`<div class="adm-item"><b>${esc(u.email)}</b><small>${esc(u.accessRole||'Profissional')}</small></div>`).join('')}</div></div></div>`;$('admClose').onclick=()=>root.remove();root.querySelectorAll('[data-ok]').forEach(b=>b.onclick=()=>approve(b.dataset.ok));root.querySelectorAll('[data-no]').forEach(b=>b.onclick=()=>reject(b.dataset.no))}
function open(){if(!isCeo())return;let root=$('captaupAdmPanel');if(root)root.remove();root=document.createElement('div');root.id='captaupAdmPanel';root.className='adm-overlay';document.body.appendChild(root);render()}
function updateBadge(){const btn=$('captaupAdmBtn');if(!btn)return;const d=data();const n=d?d.req.filter(r=>r.status==='pending').length:0;btn.innerHTML=`ADM${n?`<span class="adm-badge">${n}</span>`:''}`}
function mount(){css();if(!isCeo())return;const chip=$('captaupUserChip');if(!chip){setTimeout(mount,150);return}if(!$('captaupAdmBtn')){const b=document.createElement('button');b.id='captaupAdmBtn';b.onclick=open;chip.insertBefore(b,chip.lastElementChild)}updateBadge()}
window.addEventListener('captaup-auth-changed',()=>setTimeout(mount,50));window.addEventListener('captaup-access-request',updateBadge);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
})();