(()=>{
'use strict';
const $=id=>document.getElementById(id), qs=(s,r=document)=>Array.from(r.querySelectorAll(s));
const state={rows:[],filtered:[],rank:'vgv',page:'visao'};
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
const pct=n=>((Number(n)||0)*100).toFixed(1).replace('.',',')+'%';
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function val(o,keys){for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k]}const nk=keys.map(norm);for(const k of Object.keys(o||{})){if(nk.includes(norm(k)))return o[k]}return ''}
function number(v){if(typeof v==='number')return isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/R\$|\s/g,'');if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s.replace(/[^0-9.-]/g,''));return isFinite(n)?n:0}
function date(v){if(!v)return '';if(v instanceof Date)return v.toISOString().slice(0,10);let s=String(v).trim();let m=s.match(/^(\d{2})[\/.-](\d{2})[\/.-](\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})[\/.-](\d{2})[\/.-](\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:''}
function normalize(o){return {raw:o,date:date(val(o,['data','date','Data','DATA','dt','created_at','createdAt','Data de atendimento','_date'])),promotor:String(val(o,['promotor','Promotor','PROMOTOR','captador','Captador','Promotor de marketing'])||'').trim(),liner:String(val(o,['liner','Liner','LINER','consultor','Consultoria'])||'').trim(),closer:String(val(o,['closer','Closer','CLOSER'])||'').trim(),local:String(val(o,['local','Local','LOCAL','ponto','Ponto','Local Captação'])||'').trim(),vgv:number(val(o,['vgv','VGV','Vgv','valor_vgv','valorVgv','valor','Valor','venda','Venda','valor_venda','Valor vendido','_v'])),casal:1,q:String(val(o,['q','Q','qualificado','Qualificado','qualificacao','Qualificação','Motivo de qualificação','_q'])||'').trim(),nq:String(val(o,['nq','NQ','nao_qualificado','Não Qualificado'])||'').trim(),tour:String(val(o,['tour','Tour','visita','Visita'])||'').trim(),cidade:String(val(o,['Cidade','cidade','City'])||'').trim(),prof1:String(val(o,['Profissão 1','Profissao 1','Profissão','Profissao','profissao'])||'').trim(),prof2:String(val(o,['Profissão 2','Profissao 2'])||'').trim(),renda:number(val(o,['Renda','renda','_income'])),idade1:number(val(o,['Idade 1','Idade1','idade'])),idade2:number(val(o,['Idade 2','Idade2'])),residencia:String(val(o,['Residência própria','Residencia propria','residencia'])||'').trim(),hour:number(val(o,['_hour','hora','Hora'])||0)}}
function flatten(x){if(Array.isArray(x))return x.flatMap(flatten);if(x&&typeof x==='object'){const vals=Object.values(x);if(vals.every(v=>v&&typeof v==='object'&&!Array.isArray(v)))return vals.flatMap(flatten);return [x]}return []}
async function load(){try{const r=await fetch('./data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();state.rows=flatten(j).map(normalize).filter(r=>r.promotor||r.vgv||r.date||r.local);if(!state.rows.length)throw Error('Base sem registros');buildFilters();apply()}catch(e){console.error(e);document.querySelectorAll('.kpi').forEach(x=>x.textContent='0');const h=$('highlight');if(h)h.innerHTML='<div class="alert"><b>Erro ao carregar a base.</b><p>data.json não foi carregado ou não contém registros compatíveis.</p></div>'}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addDynamicFilters(){const box=document.querySelector('.filters');if(!box||$('cidadeFilter'))return;const defs=[['cidadeFilter','CIDADE','cidade'],['profissaoFilter','PROFISSÃO','profissao'],['rendaFilter','RENDA','renda'],['idadeFilter','IDADE','idade'],['residenciaFilter','RESIDÊNCIA','residencia']];defs.forEach(([id,label])=>{const f=document.createElement('div');f.className='field';f.innerHTML=`<label>${label}</label><select id="${id}"></select>`;box.appendChild(f)});$('rendaFilter').innerHTML='<option value="">Todas</option><option value="0-10000">Até R$ 10 mil</option><option value="10000-20000">R$ 10–20 mil</option><option value="20000-30000">R$ 20–30 mil</option><option value="30000-50000">R$ 30–50 mil</option><option value="50000+">Acima de R$ 50 mil</option>';$('idadeFilter').innerHTML='<option value="">Todas</option><option value="18-30">18–30</option><option value="31-40">31–40</option><option value="41-50">41–50</option><option value="51-60">51–60</option><option value="61+">61+</option>';['cidadeFilter','profissaoFilter','residenciaFilter'].forEach(id=>$(id).addEventListener('change',apply));$('rendaFilter').addEventListener('change',apply);$('idadeFilter').addEventListener('change',apply)}
function opts(id,field){const el=$(id);if(!el)return;const vals=[...new Set(state.rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));el.innerHTML='<option value="">Todos</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function buildFilters(){addDynamicFilters();opts('promotor','promotor');opts('liner','liner');opts('closer','closer');opts('local','local');opts('cidadeFilter','cidade');const prof=[...new Set(state.rows.flatMap(r=>[r.prof1,r.prof2]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));if($('profissaoFilter'))$('profissaoFilter').innerHTML='<option value="">Todas</option>'+prof.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');opts('residenciaFilter','residencia');const ds=state.rows.map(r=>r.date).filter(Boolean).sort();if(ds.length){$('start').value=$('start').value||ds[0];$('end').value=$('end').value||ds[ds.length-1]}}
function inRange(v,s,e){if(!v)return true;const [a,b]=v.split('-').map(Number);if(v.endsWith('+'))return a;return {a,b}}
function apply(){let a=state.rows.slice();const st=$('start')?.value,en=$('end')?.value,p=$('promotor')?.value,l=$('liner')?.value,c=$('closer')?.value,lo=$('local')?.value,ci=$('cidadeFilter')?.value,pr=$('profissaoFilter')?.value,re=$('rendaFilter')?.value,ag=$('idadeFilter')?.value,rs=$('residenciaFilter')?.value;if(st)a=a.filter(r=>!r.date||r.date>=st);if(en)a=a.filter(r=>!r.date||r.date<=en);if(p)a=a.filter(r=>r.promotor===p);if(l)a=a.filter(r=>r.liner===l);if(c)a=a.filter(r=>r.closer===c);if(lo)a=a.filter(r=>r.local===lo);if(ci)a=a.filter(r=>r.cidade===ci);if(pr)a=a.filter(r=>r.prof1===pr||r.prof2===pr);if(rs)a=a.filter(r=>r.residencia===rs);if(re){a=a.filter(r=>{const x=r.renda;if(re==='50000+')return x>50000;const [mn,mx]=re.split('-').map(Number);return x>=mn&&x<=mx})}if(ag){a=a.filter(r=>{const x=Math.max(r.idade1||0,r.idade2||0);if(ag==='61+')return x>=61;const [mn,mx]=ag.split('-').map(Number);return x>=mn&&x<=mx})}state.filtered=a;render()}
function aggregate(a){const v=a.reduce((s,r)=>s+r.vgv,0),sales=a.filter(r=>r.vgv>0).length,atend=a.length;return {v,sales,atend,conv:atend?sales/atend:0,ticket:sales?v/sales:0,per:atend?v/atend:0}}
function render(){const a=state.filtered,m=aggregate(a);if($('vgv'))$('vgv').textContent=money(m.v);if($('casais'))$('casais').textContent=num(m.atend);if($('vendas'))$('vendas').textContent=num(m.sales);if($('conv'))$('conv').textContent=pct(m.conv);if($('ticket'))$('ticket').textContent=money(m.ticket);if($('vgvCasal'))$('vgvCasal').textContent=money(m.per);if($('vgvSub'))$('vgvSub').textContent=`${num(m.sales)} vendas · ${pct(m.conv)} conversão`;if($('convSub'))$('convSub').textContent=`Q: ${num(a.filter(r=>norm(r.q)==='q').length)} · NQ: ${num(a.filter(r=>norm(r.q)==='nq').length)}`;if($('vgvProg'))$('vgvProg').style.width=Math.min(100,m.v/61700089.96*100)+'%';renderRanking();renderTeam();renderFunnel();renderHighlight();renderInsights();renderAlerts();renderSimple();renderProfile();drawDaily();drawHours();updateFilteredCount()}
function groups(a,field){const map=new Map();a.forEach(r=>{const k=r[field]||'Não informado';if(!map.has(k))map.set(k,[]);map.get(k).push(r)});return [...map].map(([name,rows])=>({name,rows,m:aggregate(rows)}))}
function table(arr){if(!arr.length)return '<div class="empty">Nenhum registro encontrado.</div>';return `<div class="tablewrap"><table><thead><tr><th>#</th><th>Promotor</th><th>VGV</th><th>Vendas</th><th>Conversão</th><th>Atendimentos</th></tr></thead><tbody>${arr.map((x,i)=>`<tr><td class="ranknum">${i+1}</td><td>${esc(x.name)}</td><td class="money">${money(x.m.v)}</td><td>${num(x.m.sales)}</td><td>${pct(x.m.conv)}</td><td>${num(x.m.atend)}</td></tr>`).join('')}</tbody></table></div>`}
function renderRanking(){let arr=groups(state.filtered,'promotor');const key=state.rank==='vendas'?'sales':state.rank==='conv'?'conv':state.rank==='casais'?'atend':'v';arr.sort((a,b)=>b.m[key]-a.m[key]);if($('rankingTable'))$('rankingTable').innerHTML=table(arr.slice(0,30));if($('rankingFull'))$('rankingFull').innerHTML=table(arr)}
function renderTeam(){if($('teamTable'))$('teamTable').innerHTML=table(groups(state.filtered,'promotor'))}
function funnelHTML(a){const m=aggregate(a),q=a.filter(r=>norm(r.q)==='q').length,nq=a.filter(r=>norm(r.q)==='nq').length;return [['ABORDAGENS',m.atend,''],['QUALIFICADOS',q,'q'],['NÃO QUALIFICADOS',nq,'t'],['VENDAS',m.sales,'s']].map(x=>`<div class="funnelrow"><div class="funnelbar ${x[2]}" style="width:${Math.max(80,Math.min(100,(x[1]/Math.max(1,m.atend))*100))}%">${esc(x[0])}</div><div class="ftxt">${num(x[1])}</div></div>`).join('')}
function renderFunnel(){const h=funnelHTML(state.filtered);if($('funnel'))$('funnel').innerHTML=h;if($('funnel2'))$('funnel2').innerHTML=h;if($('motives')){const g=groups(state.filtered,'q');$('motives').innerHTML=`<div class="metricgrid"><div class="metricbox">Q<strong>${num(state.filtered.filter(r=>norm(r.q)==='q').length)}</strong></div><div class="metricbox">NQ<strong>${num(state.filtered.filter(r=>norm(r.q)==='nq').length)}</strong></div><div class="metricbox">Vendas<strong>${num(state.filtered.filter(r=>r.vgv>0).length)}</strong></div></div>`}}
function renderHighlight(){const el=$('highlight');if(!el)return;const g=groups(state.filtered,'promotor').sort((a,b)=>b.m.v-a.m.v)[0];el.innerHTML=g?`<div class="person"><div class="avatar">${esc(g.name.slice(0,1).toUpperCase())}</div><div><b>${esc(g.name)}</b><div class="badge">TOP VGV</div></div></div><div class="stats"><div class="stat">VGV <b>${money(g.m.v)}</b></div><div class="stat">Vendas <b>${num(g.m.sales)}</b></div><div class="stat">Conversão <b>${pct(g.m.conv)}</b></div><div class="stat">Atendimentos <b>${num(g.m.atend)}</b></div></div>`:'<div class="empty">Sem dados.</div>'}
function renderInsights(){const e=$('insights');if(!e)return;const m=aggregate(state.filtered);e.innerHTML=`<div class="insight"><b>Resumo</b><p>${num(m.sales)} vendas em ${num(m.atend)} atendimentos, com conversão de ${pct(m.conv)} e VGV de ${money(m.v)}.</p></div><div class="info"><b>Registros filtrados:</b> ${num(state.filtered.length)} de ${num(state.rows.length)}</div>`}
function renderAlerts(){const e=$('alerts');if(!e)return;const m=aggregate(state.filtered);e.innerHTML=(m.conv<.2?'<div class="alert"><b>⚠️ Conversão abaixo de 20%.</b><p>Revise abordagem e qualificação.</p></div>':'<div class="info">✅ Conversão acima de 20%.</div>')+`<div class="info"><b>Central de alertas e oportunidades</b><br>VGV: ${money(m.v)} · Vendas: ${num(m.sales)} · Atendimentos: ${num(m.atend)}</div>`}
function renderSimple(){const loc=$('locations');if(loc)loc.innerHTML=groups(state.filtered,'local').sort((a,b)=>b.m.v-a.m.v).slice(0,20).map(g=>`<div class="stat"><span>${esc(g.name)}</span><b>${money(g.m.v)}</b></div>`).join('')||'<div class="empty">Sem dados.</div>'}
function renderProfile(){const e=$('profileTable');if(!e)return;const city=groups(state.filtered,'cidade').sort((a,b)=>b.rows.length-a.rows.length).slice(0,20);const profMap=new Map();state.filtered.forEach(r=>[r.prof1,r.prof2].forEach(p=>{if(p)profMap.set(p,(profMap.get(p)||0)+1)}));const prof=[...profMap].sort((a,b)=>b[1]-a[1]).slice(0,20);const income=state.filtered.filter(r=>r.renda>0).map(r=>r.renda);const avg=income.length?income.reduce((a,b)=>a+b,0)/income.length:0;e.innerHTML=`<div class="metricgrid"><div class="metricbox">Cidades<strong>${num(city.length)}</strong></div><div class="metricbox">Profissões<strong>${num(prof.length)}</strong></div><div class="metricbox">Renda média<strong>${money(avg)}</strong></div></div><h4>Cidades</h4>${city.map(g=>`<div class="stat"><span>${esc(g.name)}</span><b>${num(g.rows.length)}</b></div>`).join('')||'<div class="empty">Sem cidades.</div>'}<h4>Profissões</h4>${prof.map(([p,n])=>`<div class="stat"><span>${esc(p)}</span><b>${num(n)}</b></div>`).join('')||'<div class="empty">Sem profissões.</div>'}<h4>Renda</h4><div class="info">Renda média dos registros com renda informada: <b>${money(avg)}</b>.</div>`}
function updateFilteredCount(){qs('[data-filter-count]').forEach(e=>e.textContent=num(state.filtered.length))}
function drawDaily(){const c=$('daily');if(!c)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth*dpr,h=c.clientHeight*dpr;c.width=w;c.height=h;ctx.clearRect(0,0,w,h);const by={};state.filtered.forEach(r=>{const d=r.date||'Sem data';if(!by[d])by[d]={v:0};by[d].v+=r.vgv});const ds=Object.keys(by).sort();if(!ds.length){ctx.fillStyle='#8d99aa';ctx.font=14*dpr+'px sans-serif';ctx.fillText('Sem dados para o período',20,40);return}const max=Math.max(1,...ds.map(d=>by[d].v)),pad=35*dpr;ctx.strokeStyle='#1683ff';ctx.lineWidth=2*dpr;ctx.beginPath();ds.forEach((d,i)=>{const x=pad+(w-pad*2)*(i/Math.max(1,ds.length-1)),y=h-pad-(h-pad*2)*(by[d].v/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function drawHours(){const c=$('hours');if(!c)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth*dpr,h=c.clientHeight*dpr;c.width=w;c.height=h;ctx.clearRect(0,0,w,h);const by={};state.filtered.forEach(r=>{const hr=Number(r.hour);if(!isFinite(hr))return;if(!by[hr])by[hr]={n:0,v:0};by[hr].n++;by[hr].v+=r.vgv});const hs=Object.keys(by).map(Number).sort((a,b)=>a-b);if(!hs.length){ctx.fillStyle='#8d99aa';ctx.font=14*dpr+'px sans-serif';ctx.fillText('Sem horário disponível',20,40);return}const max=Math.max(1,...hs.map(hh=>by[hh].v)),pad=30*dpr,bw=(w-pad*2)/hs.length*.7;ctx.fillStyle='#1683ff';hs.forEach((hh,i)=>{const x=pad+i*((w-pad*2)/hs.length),bh=(h-pad*2)*(by[hh].v/max);ctx.fillRect(x,h-pad-bh,bw,bh);ctx.fillStyle='#8d99aa';ctx.font=10*dpr+'px sans-serif';ctx.fillText(String(hh).padStart(2,'0')+'h',x,h-8*dpr);ctx.fillStyle='#1683ff'})}
function nav(page){state.page=page;qs('[id^="page-"]').forEach(x=>x.hidden=x.id!==`page-${page}`);qs('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));qs('.mobilebar button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados'};if($('pageTitle'))$('pageTitle').textContent=titles[page]||'FluxoHub'}
function bind(){document.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n){e.preventDefault();nav(n.dataset.page);return}const r=e.target.closest('[data-rank]');if(r){e.preventDefault();state.rank=r.dataset.rank;qs('[data-rank]').forEach(x=>x.classList.toggle('active',x===r));renderRanking();return}});['start','end','promotor','liner','closer','local'].forEach(id=>$(id)?.addEventListener('change',apply));$('reset')?.addEventListener('click',()=>{['start','end','promotor','liner','closer','local','cidadeFilter','profissaoFilter','rendaFilter','idadeFilter','residenciaFilter'].forEach(id=>{const e=$(id);if(e)e.value=''});buildFilters();apply()});$('importBtn')?.addEventListener('click',()=>$('file')?.click());$('file')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text();const lines=text.split(/\r?\n/).filter(Boolean);const sep=lines[0].includes(';')?';':',';const heads=lines[0].split(sep).map(x=>x.replace(/^"|"$/g,''));state.rows=lines.slice(1).map(line=>{const c=line.split(sep),o={};heads.forEach((h,i)=>o[h]=(c[i]||'').replace(/^"|"$/g,''));return normalize(o)});buildFilters();apply()});$('export')?.addEventListener('click',()=>{const csv=['PROMOTOR,VGV,VENDAS,CONVERSAO,ATENDIMENTOS',...groups(state.filtered,'promotor').map(g=>[JSON.stringify(g.name),g.m.v,g.m.sales,(g.m.conv*100).toFixed(2),g.m.atend].join(','))].join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const x=document.createElement('a');x.href=u;x.download='fluxohub-export.csv';x.click();URL.revokeObjectURL(u)})}
function init(){bind();nav('visao');load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();