(function(){
'use strict';
const USERS_KEY='captaup_auth_users_v2';
const REQUESTS_KEY='captaup_access_requests_v1';
const SESSION_KEY='captaup_auth_session_v2';
const PROFILE_KEY='captaup_user_profile_v2';
const CEO_EMAILS=['raphaelbuenosuporte@gmail.com','raphaelbueno.captacao@gmail.com'];
const $=id=>document.getElementById(id);
const norm=s=>String(s||'').trim().toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function read(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function seedUsers(){const u=read(USERS_KEY,{});for(const email of CEO_EMAILS){if(!u[email])u[email]={email,name:'RAPHAEL BUENO DA SILVA',accessRole:'CEO',performanceRole:'admin',active:true,approved:true}}write(USERS_KEY,u);return u}
function session(){return read(SESSION_KEY,null)}
function setSession(user){const s={email:user.email,name:user.name||user.email,accessRole:user.accessRole||'Profissional',performanceRole:user.performanceRole||'promotor',at:Date.now()};write(SESSION_KEY,s);write(PROFILE_KEY,s);window.__captaupUser=s;window.dispatchEvent(new CustomEvent('captaup-auth-changed',{detail:s}))}
function initials(name){return String(name||'CU').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function css(){if($('captaup-auth-css'))return;const s=document.createElement('style');s.id='captaup-auth-css';s.textContent=`#captaupAuth{position:fixed;inset:0;z-index:100000;background:radial-gradient(circle at 50% 15%,#0d2740 0,#07111b 38%,#02070d 100%);display:grid;place-items:center;padding:20px;font-family:inherit;color:#eaf7ff}.ca-box{width:min(440px,100%);border:1px solid #1c4e72;border-radius:22px;background:linear-gradient(155deg,#091724,#06101a);box-shadow:0 34px 90px #000c,0 0 70px #138cf522;padding:26px}.ca-logo{display:flex;align-items:center;gap:12px;margin-bottom:20px}.ca-mark{width:46px;height:46px;border-radius:14px;background:linear-gradient(135deg,#1683ff,#5f4dff);display:grid;place-items:center;font-size:24px;font-weight:950}.ca-brand{font-weight:950;font-size:20px}.ca-brand small{display:block;font-size:8px;letter-spacing:2px;color:#7696ae}.ca-title{font-size:22px;font-weight:950;margin:8px 0 5px}.ca-sub{font-size:10px;line-height:1.5;color:#86a0b4;margin-bottom:18px}.ca-field label{display:block;font-size:8px;color:#7893a7;margin:0 0 6px;letter-spacing:1px}.ca-field input{width:100%;box-sizing:border-box;border-radius:12px;border:1px solid #23465e;background:#05101a;color:#f5fbff;padding:13px 14px}.ca-btn{width:100%;margin-top:14px;border:0;border-radius:12px;padding:13px;background:linear-gradient(135deg,#1683ff,#3f6bff);color:#fff;font-weight:950;cursor:pointer}.ca-msg{min-height:16px;margin-top:10px;color:#ffb27a;font-size:9px}.ca-safe{margin-top:14px;padding:10px;border:1px solid #183a51;border-radius:10px;background:#071521;color:#6f8da2;font-size:8px;line-height:1.5}.ca-user{display:flex;align-items:center;gap:8px;margin-left:auto;padding:6px 8px;border:1px solid #1d4d6f;background:#071724;border-radius:999px}.ca-avatar{width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#1683ff,#6d4cff);display:grid;place-items:center;font-size:10px;font-weight:950}.ca-meta{font-size:8px;line-height:1.2;color:#88a2b6}.ca-meta b{display:block;color:#eaf7ff;font-size:9px;max-width:160px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ca-logout{border:0;background:transparent;color:#7ba8c5;font-size:8px;cursor:pointer}@media(max-width:700px){.ca-meta{display:none}}`;document.head.appendChild(s)}
function renderUserChip(user){const top=document.querySelector('.top');if(!top)return;let chip=$('captaupUserChip');if(!chip){chip=document.createElement('div');chip.id='captaupUserChip';top.appendChild(chip)}chip.className='ca-user';chip.innerHTML=`<div class="ca-avatar">${esc(initials(user.name))}</div><div class="ca-meta"><b>${esc(user.name)}</b>${esc(user.accessRole)}</div><button class="ca-logout" id="captaupLogout">SAIR</button>`;$('captaupLogout').onclick=()=>{localStorage.removeItem(SESSION_KEY);localStorage.removeItem(PROFILE_KEY);location.reload()}}
function showLogin(){let root=$('captaupAuth');if(root)root.remove();root=document.createElement('div');root.id='captaupAuth';root.innerHTML=`<div class="ca-box"><div class="ca-logo"><div class="ca-mark">C</div><div class="ca-brand">CAPTAUP<small>ACESSO POR APROVAÇÃO</small></div></div><div id="caBody"></div></div>`;document.body.appendChild(root);showEmail()}
function showEmail(){const body=$('caBody');body.innerHTML=`<div class="ca-title">Entrar na operação</div><div class="ca-sub">Digite seu e-mail. Se já estiver aprovado, você entra. Se ainda não estiver, envia um pedido para o CEO/ADM.</div><div class="ca-field"><label>E-MAIL</label><input id="caEmail" type="email" autocomplete="email" placeholder="seuemail@empresa.com"></div><button class="ca-btn" id="caContinue">CONTINUAR</button><div class="ca-msg" id="caMsg"></div><div class="ca-safe">Sem senha. O controle de acesso é feito pela aprovação do e-mail dentro do CAPTAUP.</div>`;$('caContinue').onclick=checkEmail;$('caEmail').onkeydown=e=>{if(e.key==='Enter')checkEmail()};$('caEmail').focus()}
function requestAccess(email){const req=read(REQUESTS_KEY,[]);if(!req.some(r=>r.email===email&&r.status==='pending'))req.push({id:Date.now(),email,status:'pending',requestedAt:new Date().toISOString()});write(REQUESTS_KEY,req);window.dispatchEvent(new Event('captaup-access-request'));$('caMsg').textContent='Pedido enviado. Aguarde a aprovação do CEO/ADM.'}
function checkEmail(){const email=norm($('caEmail').value);if(!email||!email.includes('@')){$('caMsg').textContent='Digite um e-mail válido.';return}const u=seedUsers();const user=u[email];if(user&&user.active&&user.approved){setSession(user);$('captaupAuth').remove();renderUserChip(user);return}requestAccess(email)}
function boot(){css();seedUsers();const s=session();if(s&&s.email){window.__captaupUser=s;write(PROFILE_KEY,s);renderUserChip(s);window.dispatchEvent(new CustomEvent('captaup-auth-changed',{detail:s}))}else showLogin()}
window.CAPTAUP_AUTH={usersKey:USERS_KEY,requestsKey:REQUESTS_KEY,sessionKey:SESSION_KEY,profileKey:PROFILE_KEY,read,write};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
