(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function api(){return window.CAPTAUP_AUTH}
function isCEO(){return String(window.__captaupUser?.accessRole||'').toUpperCase()==='CEO'||String(window.__captaupUser?.accessRole||'').toUpperCase().includes('ADM')}
function css(){if($('captaup-admin-css'))return;const s=document.createElement('style');s.id='captaup-admin-css';s.textContent=`#admPanel{position:fixed;right:16px;top:72px;z-index:9998;width:min(430px,calc(100vw - 32px));max-height:75vh;overflow:auto;background:#07131e;border:1px solid #245777;border-radius:16px;box-shadow:0 24px 70px #000b;padding:14px;color:#eaf7ff;display:none}.adm-fab{position:fixed;right:18px;bottom:18px;z-index:9997;border:0;border-radius:999px;background:linear-gradient(135deg,#1683ff,#5f4dff);color:#fff;padding:12px 16px;font-size:10px;font-weight:950;box-shadow:0 12px 35px #1683ff55;cursor:pointer}.adm-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.adm-title{font-weight:950}.adm-count{font-size:9px;color:#89a8bc}.adm-list{display:grid;gap:9px;margin-top:12px}.adm-item{border:1px solid #18394f;border-radius:12px;padding:10px;background:#08111a}.adm-email{font-size:10px;font-weight:900;word-break:break-all}.adm-meta{font-size:8px;color:#7792a6;margin-top:4px}.adm-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.adm-actions select{grid-column:1/3;background:#06101a;border:1px solid #27475d;color:#eaf7ff;border-radius:8px;padding:8px;font-size:9px}.adm-btn{border:0;border-radius:8px;padding:8px;font-size:9px;font-weight:900;cursor:pointer}.adm-ok{background:#18b86a;color:white}.adm-no{background:#3a1620;color:#ffb8c5}.adm-empty{padding:18px;text-align:center;color:#7895a7;font-size:9px}.adm-close{border:0;background:transparent;color:#89a8bc;cursor:pointer}`;document.head.appendChild(s)}
function mount(){if(!isCEO())return;if($('admFab'))return;css();const fab=document.createElement('button');fab.id='admFab';fab.className='adm-fab';fab.textContent='ADM';document.body.appendChild(fab);const panel=document.createElement('div');panel.id='admPanel';document.body.appendChild(panel);fab.onclick=()=>{panel.style.display=panel.style.display==='block'?'none':'block';render()};window.addEventListener('captaup-access-request',render);render()}
function render(){if(!isCEO()||!api())return;const a=api(),req=a.read(a.requestsKey,[]).filter(r=>r.status==='pending');const p=$('admPanel');if(!p)return;p.innerHTML=`<div class="adm-head"><div><div class="adm-title">ADM • Aprovação de Acessos</div><div class="adm-count">${req.length} pedido(s) pendente(s)</div></div><button class="adm-close" id="admClose">✕</button></div><div class="adm-list">${req.length?req.map(r=>`<div class="adm-item"><div class="adm-email">${esc(r.email)}</div><div class="adm-meta">Pedido de acesso</div><div class="adm-actions"><select data-role="${r.id}"><option value="promotor">Promotor</option><option value="liner">Liner</option><option value="closer">Closer</option><option value="lider">Líder</option><option value="admin">Administrador</option></select><button class="adm-btn adm-ok" data-approve="${r.id}">APROVAR</button><button class="adm-btn adm-no" data-deny="${r.id}">RECUSAR</button></div></div>`).join(''):'<div class="adm-empty">Nenhum pedido pendente.</div>'}</div>`;$('admClose').onclick=()=>p.style.display='none';p.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(+b.dataset.approve));p.querySelectorAll('[data-deny]').forEach(b=>b.onclick=()=>deny(+b.dataset.deny))}
function approve(id){const a=api(),req=a.read(a.requestsKey,[]),r=req.find(x=>x.id===id);if(!r)return;const sel=document.querySelector(`[data-role="${id}"]`),role=sel?.value||'promotor';const users=a.read(a.usersKey,{});users[r.email]={email:r.email,name:r.email.split('@')[0].toUpperCase(),accessRole:role==='admin'?'Administrador':'Profissional',performanceRole:role,active:true,approved:true};r.status='approved';r.approvedAt=new Date().toISOString();a.write(a.usersKey,users);a.write(a.requestsKey,req);render()}
function deny(id){const a=api(),req=a.read(a.requestsKey,[]),r=req.find(x=>x.id===id);if(!r)return;r.status='denied';r.deniedAt=new Date().toISOString();a.write(a.requestsKey,req);render()}
window.addEventListener('captaup-auth-changed',mount);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
})();
