(()=>{'use strict';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function unpack(p){if(!(p&&Array.isArray(p.d)&&Array.isArray(p.r)))return[];const[P]=p.d;return p.r.map(a=>({date:a[0],promotor:String(P[a[1]]||'').trim(),vgv:+a[5]||0,activeV:+a[8]||0,sales:+a[7]||0,activeSales:+a[9]||0})).filter(r=>r.date)}
function active(name){return typeof window.CAPTAUP_IS_ACTIVE==='function'?window.CAPTAUP_IS_ACTIVE(name):true}
function aggregate(rows){const m=new Map();for(const r of rows){if(!active(r.promotor))continue;if(!m.has(r.promotor))m.set(r.promotor,{name:r.promotor,casais:0,activeV:0,sales:0});const x=m.get(r.promotor);x.casais++;x.activeV+=r.activeV;x.sales+=r.sales}return[...m.values()]}
function lastDate(rows){return rows.map(r=>r.date).sort().at(-1)||''}
function installFilterToggle(){const filters=document.querySelector('.filters');if(!filters||document.querySelector('.filter-toggle'))return;const b=document.createElement('button');b.className='filter-toggle';b.type='button';b.innerHTML='<span>Filtros</span><span id="filterToggleMeta">Abrir</span>';filters.parentNode.insertBefore(b,filters);const sync=()=>{if(innerWidth<=760&&!filters.classList.contains('mobile-open'))filters.classList.add('mobile-collapsed');else if(innerWidth>760){filters.classList.remove('mobile-collapsed','mobile-open')}};b.onclick=()=>{const open=filters.classList.toggle('mobile-open');filters.classList.toggle('mobile-collapsed',!open);$('filterToggleMeta').textContent=open?'Fechar':'Abrir'};addEventListener('resize',sync);sync()}
function installToday(rows){const hero=document.querySelector('.hero');if(!hero||document.querySelector('.today-strip'))return;const d=lastDate(rows);const todayRows=rows.filter(r=>r.date===d);const a=aggregate(todayRows),casais=todayRows.length,vendas=todayRows.reduce((s,r)=>s+r.sales,0),vgv=todayRows.reduce((s,r)=>s+r.activeV,0);const box=document.createElement('div');box.className='today-strip';box.innerHTML=`<div class="today-label"><b>Resumo do último dia disponível</b><span>${d?d.split('-').reverse().join('/'):'Sem data disponível'} · atualização operacional</span></div><div class="today-mini"><small>Casais</small><strong class="good">${num(casais)}</strong></div><div class="today-mini"><small>Vendas</small><strong>${num(vendas)}</strong></div><div class="today-mini"><small>VGV líquido</small><strong class="money">${money(vgv)}</strong></div>`;hero.insertAdjacentElement('afterend',box)}
function decorateTables(){if(innerWidth>760)return;['rankingTable','rankingTableFull','promotorTable','linerTable','closerTable','rulesTable'].forEach(id=>{const host=$(id);if(!host)return;host.querySelectorAll('.tablewrap').forEach(w=>w.classList.add('mobile-cards'))})}
function buildPodium(rows){const host=$('rankingTop3');if(!host)return;const st=$('start')?.value||'',en=$('end')?.value||'';const filtered=rows.filter(r=>(!st||r.date>=st)&&(!en||r.date<=en));const top=aggregate(filtered).sort((a,b)=>b.casais-a.casais||b.sales-a.sales||b.activeV-a.activeV).slice(0,3);if(!top.length)return;const order=[top[1],top[0],top[2]].filter(Boolean);host.innerHTML=`<div class="rank-podium">${order.map((x,i)=>{const pos=x===top[0]?1:x===top[1]?2:3;return `<div class="podium-card ${pos===1?'first':''}"><div class="medal">${pos===1?'🥇':pos===2?'🥈':'🥉'}</div><div class="pos">${pos}º LUGAR</div><div class="name">${x.name}</div><div class="value">${num(x.casais)} casais</div><div class="meta">${num(x.sales)} vendas · ${money(x.activeV)}</div></div>`}).join('')}</div>`}
function observe(){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{decorateTables()},50)}).observe(document.documentElement,{childList:true,subtree:true})}
async function boot(){installFilterToggle();if(typeof window.loadCaptaUpAnnual!=='function'){setTimeout(boot,160);return}try{const rows=unpack(await window.loadCaptaUpAnnual());installToday(rows);buildPodium(rows);['start','end'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(()=>buildPodium(rows),20)));document.querySelectorAll('[data-page="ranking"]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{buildPodium(rows);decorateTables()},60)));decorateTables();observe()}catch(e){console.warn('CAPTAUP UI',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();