(function(){
'use strict';
/* Filtros contextuais opcionais para tabelas/rankings do FluxoHub. */
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
function addStyle(){if(document.getElementById('context-filter-style'))return;const s=document.createElement('style');s.id='context-filter-style';s.textContent='.context-filter{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0 14px}.context-filter select{min-width:145px;padding:9px 10px;border-radius:8px}.context-filter label{font-size:11px;font-weight:700;display:flex;flex-direction:column;gap:4px}.context-filter .cf-reset{padding:9px 12px;border-radius:8px;cursor:pointer}.context-filter-title{font-size:12px;font-weight:800;margin:8px 0}.cf-hidden{display:none!important}';document.head.appendChild(s)}
function makeFilter(container,items,apply){if(!container)return;container.classList.add('context-filter');container.innerHTML='<div class="context-filter-title">FILTROS OPCIONAIS</div>';items.forEach(it=>{const lab=document.createElement('label');lab.innerHTML=it.label+'<select data-cf="'+it.key+'"><option value="">Todos</option>'+it.values.map(v=>'<option>'+String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</option>').join('')+'</select>';container.appendChild(lab)});const b=document.createElement('button');b.className='cf-reset';b.textContent='Limpar filtros';b.onclick=()=>{container.querySelectorAll('select').forEach(s=>s.value='');apply({})};container.appendChild(b);container.querySelectorAll('select').forEach(s=>s.onchange=()=>{const o={};container.querySelectorAll('select').forEach(x=>o[x.dataset.cf]=x.value);apply(o)})}
function values(rows,key){return [...new Set(rows.map(x=>String(x[key]??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function mount(){addStyle();const sections=[['page-equipe','#teamTable',['promotor','liner','closer','local']],['page-ranking','#rankingTable',['promotor','liner','closer','local']],['page-operacao','#locations',['local','liner','closer']],['page-perfil','#profileTable',['cidade','profissao','promotor','local']],['page-alertas','#alertList',['promotor','local']]];const data=window.__FLUXOHUB_DATA__||[];const defs={promotor:'Promotor de marketing',liner:'Liner',closer:'Closer',local:'Local Captação',cidade:'Cidade',profissao:'Profissão 1'};sections.forEach(([page,target,keys])=>{const sec=document.getElementById(page),table=document.querySelector(target);if(!sec||!table||sec.querySelector('.context-filter'))return;const box=document.createElement('div');box.className='context-filter-wrap';table.parentNode.insertBefore(box,table);makeFilter(box,keys.map(k=>({key:k,label:k==='promotor'?'Promotor':k==='liner'?'Liner':k==='closer'?'Closer':k==='local'?'Local':k==='cidade'?'Cidade':'Profissão',values:values(data,defs[k])})),filters=>{qsa(target+' tbody tr').forEach(tr=>{const txt=tr.textContent.toLowerCase();let ok=true;Object.values(filters).forEach(v=>{if(v&&!txt.includes(v.toLowerCase()))ok=false});tr.classList.toggle('cf-hidden',!ok)})})})}
function boot(){setTimeout(mount,1200);setTimeout(mount,3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();