(function(){
'use strict';
const $=id=>document.getElementById(id);
let data=[];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const num=v=>new Intl.NumberFormat('pt-BR').format(Number(v)||0);
const pct=v=>(Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
function val(v){if(v==null||v==='')return 0;let s=String(v).replace(/R\$|\s/g,'').replace(/\./g,'').replace(',','.');return Number(s)||0}
function date(v){let m=String(v||'').match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:''}
function prep(r){return Object.assign({},r,{_date:date(r['Data de atendimento']),_v:val(r['Valor vendido']),_q:String(r['Qualificação']||'').trim().toUpperCase()})}
function filtered(){let a=$('start')?.value,b=$('end')?.value,p=$('promotor')?.value,l=$('liner')?.value,c=$('closer')?.value,lo=$('local')?.value;return data.filter(x=>(!a||x._date>=a)&&(!b||x._date<=b)&&(!p||x['Promotor de marketing']===p)&&(!l||x.Liner===l)&&(!c||x.Closer===c)&&(!lo||x['Local Captação']===lo))}
function fill(id,key){let e=$(id);if(!e)return;let values=[...new Set(data.map(x=>x[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));e.innerHTML='<option value="">Todos</option>';values.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;e.appendChild(o)})}
function rowsBy(key,a){let m=new Map();a.forEach(x=>{let k=String(x[key]||'Não informado').trim()||'Não informado';let o=m.get(k)||{name:k,casais:0,vendas:0,vgv:0,q:0,nq:0};o.casais++;o.vgv+=x._v;if(x._v>0)o.vendas++;if(x._q==='Q')o.q++;if(x._q==='NQ')o.nq++;m.set(k,o)});return [...m.values()]}
function table(rows,headers,render){if(!rows.length)return '<div class="empty">Nenhum registro no período/filtro selecionado.</div>';return '<div class="tablewrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(render).join('')+'</tbody></table></div>'}
function renderKPIs(a){let s=a.filter(x=>x._v>0),v=s.reduce((t,x)=>t+x._v,0),conv=a.length?s.length/a.length*100:0,t=s.length?v/s.length:0,q=a.filter(x=>x._q==='Q').length,nq=a.filter(x=>x._q==='NQ').length;
if($('vgv'))$('vgv').textContent=money(v);if($('vgvSub'))$('vgvSub').textContent=num(s.length)+' vendas · '+pct(conv)+' conversão';if($('casais'))$('casais').textContent=num(a.length);if($('vendas'))$('vendas').textContent=num(s.length);if($('conv'))$('conv').textContent=pct(conv);if($('convSub'))$('convSub').textContent='Q: '+num(q)+' · NQ: '+num(nq);if($('ticket'))$('ticket').textContent=money(t);if($('vgvCasal'))$('vgvCasal').textContent=money(a.length?v/a.length:0);if($('count'))$('count').textContent=num(a.length)+' registros';if($('vgvProg'))$('vgvProg').style.width=Math.min(100,v/20000000*100)+'%';
if($('alerts'))$('alerts').innerHTML=conv<20?'<div class="alert">⚠️ <b>Conversão abaixo de 20%.</b> Revise abordagem e qualificação.</div>':'<div class="info">✅ Conversão atual: <b>'+pct(conv)+'</b></div>';
let f='<div class="funnelrow"><div class="funnelbar">ABORDAGENS</div><div class="ftxt">'+num(a.length)+'</div></div><div class="funnelrow"><div class="funnelbar q">QUALIFICADOS</div><div class="ftxt">'+num(q)+'</div></div><div class="funnelrow"><div class="funnelbar s">VENDAS</div><div class="ftxt">'+num(s.length)+'</div></div>';if($('funnel'))$('funnel').innerHTML=f;if($('funnel2'))$('funnel2').innerHTML=f;
}
function renderTeam(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv);let h=['#','PROMOTOR','ATENDIMENTOS','Q','NQ','VENDAS','CONVERSÃO','VGV','TICKET'];let html=table(r,h,(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td><td>'+money(x.vendas?x.vgv/x.vendas:0)+'</td></tr>');if($('teamTable'))$('teamTable').innerHTML=html;if($('rankingFull'))$('rankingFull').innerHTML=html}
function renderRank(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv);let html=table(r,['#','PROMOTOR','VGV','VENDAS','CONVERSÃO','ATENDIMENTOS'],(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td class="money">'+money(x.vgv)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td>'+num(x.casais)+'</td></tr>');if($('rankingTable'))$('rankingTable').innerHTML=html;if($('rankingFull'))$('rankingFull').innerHTML=html}
function renderOperation(a){let loc=rowsBy('Local Captação',a).sort((x,y)=>y.vgv-x.vgv);if($('locations'))$('locations').innerHTML=table(loc,['LOCAL','ATEND.','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderProfile(a){let cities=rowsBy('Cidade',a).sort((x,y)=>y.casais-x.casais);let prof=rowsBy('Profissão',a).sort((x,y)=>y.casais-x.casais);if($('profileTable'))$('profileTable').innerHTML=table(cities,['CIDADE','ATENDIMENTOS','VENDAS','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="money">'+money(x.vgv)+'</td></tr>');if($('profile'))$('profile').innerHTML=table(prof,['PROFISSÃO','ATENDIMENTOS','VENDAS','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderAlerts(a){let r=rowsBy('Promotor de marketing',a).filter(x=>x.casais>=5).sort((x,y)=>(x.vendas/x.casais)-(y.vendas/y.casais));if($('alertList'))$('alertList').innerHTML=table(r.slice(0,15),['PROMOTOR','ATEND.','VENDAS','CONVERSÃO'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="bad">'+pct(x.vendas/x.casais*100)+'</td></tr>');}
function renderData(a){let target=$('dataTable')||$('dadosTable')||$('rawTable');if(!target)return;let keys=['Data de atendimento','Promotor de marketing','Liner','Closer','Local Captação','Qualificação','Valor vendido'];target.innerHTML=table(a.slice(0,500),keys,x=>'<tr>'+keys.map(k=>'<td>'+((k==='Valor vendido')?money(x._v):(x[k]??''))+'</td>').join('')+'</tr>')+'<div class="ksub">Exibindo até 500 registros para manter o painel rápido. Total filtrado: '+num(a.length)+'</div>'}
function render(){let a=filtered();renderKPIs(a);renderTeam(a);renderRank(a);renderOperation(a);renderProfile(a);renderAlerts(a);renderData(a);}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>{b.onclick=function(){let p=this.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('main>section').forEach(x=>x.hidden=x.id!=='page-'+p);if($('pageTitle'))$('pageTitle').textContent={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados'}[p]||'FluxoHub';render();}})}
function start(){nav();['promotor','liner','closer','local','start','end'].forEach(id=>{let e=$(id);if(e)e.addEventListener('change',render)});if($('reset'))$('reset').onclick=function(){['promotor','liner','closer','local'].forEach(id=>{if($(id))$(id).value=''});let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';render()};render()}
fetch('./data.json?fix='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('data.json '+r.status);return r.json()}).then(j=>{data=(Array.isArray(j)?j:(j.data||j.rows||[])).map(prep);let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';fill('promotor','Promotor de marketing');fill('liner','Liner');fill('closer','Closer');fill('local','Local Captação');start()}).catch(e=>{console.error(e);nav();if($('alerts'))$('alerts').innerHTML='<div class="alert"><b>Erro ao carregar a base.</b> '+e.message+'</div>'});
})();
