(function(){
'use strict';
const $=id=>document.getElementById(id);
let data=[];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const num=v=>new Intl.NumberFormat('pt-BR').format(Number(v)||0);
const pct=v=>(Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
function val(v){if(v==null||v==='')return 0; if(typeof v==='number')return Number.isFinite(v)?v:0; let s=String(v).trim().replace(/R\$/gi,'').replace(/\s/g,''); if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.'); else if(s.includes(','))s=s.replace(',','.'); return Number(s.replace(/[^0-9.-]/g,''))||0}
function date(v){let s=String(v||'').trim();let m=s.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:/^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):''}
function clean(s){return String(s??'').trim().replace(/\s+/g,' ').toUpperCase()}
function prep(r){return Object.assign({},r,{_date:date(r['Data de atendimento']),_v:val(r['Valor vendido']),_q:clean(r['Qualificação']),_status:clean(r['Status do contrato']),_hour:(String(r['Data/Hora do cadastro']||'').match(/\s(\d{1,2}):/)||[])[1]||''})}
function dedupe(rows){const seen=new Set();return rows.filter(x=>{const k=[x['Data/Hora do cadastro'],x['Promotor de marketing'],x['Nome 1'],x['Nome 2'],x['Valor vendido'],x['Data de atendimento']].map(clean).join('|');if(seen.has(k))return false;seen.add(k);return true})}
function filtered(){let a=$('start')?.value,b=$('end')?.value,p=$('promotor')?.value,l=$('liner')?.value,c=$('closer')?.value,lo=$('local')?.value;return data.filter(x=>(!a||x._date>=a)&&(!b||x._date<=b)&&(!p||x['Promotor de marketing']===p)&&(!l||x.Liner===l)&&(!c||x.Closer===c)&&(!lo||x['Local Captação']===lo))}
function fill(id,key){let e=$(id);if(!e)return;let values=[...new Set(data.map(x=>String(x[key]??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));e.innerHTML='<option value="">Todos</option>';values.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;e.appendChild(o)})}
function rowsBy(key,a){let m=new Map();a.forEach(x=>{let k=String(x[key]||'Não informado').trim()||'Não informado';let o=m.get(k)||{name:k,casais:0,vendas:0,vgv:0,q:0,nq:0};o.casais++;o.vgv+=x._v;if(x._v>0)o.vendas++;if(x._q==='Q'||x._q.startsWith('Q '))o.q++;if(x._q==='NQ'||x._q.startsWith('NQ'))o.nq++;m.set(k,o)});return [...m.values()]}
function table(rows,headers,render){if(!rows.length)return '<div class="empty">Nenhum registro no período/filtro selecionado.</div>';return '<div class="tablewrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(render).join('')+'</tbody></table></div>'}
function baseStats(a){const s=a.filter(x=>x._v>0);const v=s.reduce((t,x)=>t+x._v,0);return {a,s,v,conv:a.length?s.length/a.length*100:0,t:s.length?v/s.length:0,q:a.filter(x=>x._q==='Q'||x._q.startsWith('Q ')).length,nq:a.filter(x=>x._q==='NQ'||x._q.startsWith('NQ')).length}}
function renderKPIs(a){let z=baseStats(a);if($('vgv'))$('vgv').textContent=money(z.v);if($('vgvSub'))$('vgvSub').textContent=num(z.s.length)+' vendas · '+pct(z.conv)+' conversão';if($('casais'))$('casais').textContent=num(a.length);if($('vendas'))$('vendas').textContent=num(z.s.length);if($('conv'))$('conv').textContent=pct(z.conv);if($('convSub'))$('convSub').textContent='Q: '+num(z.q)+' · NQ: '+num(z.nq);if($('ticket'))$('ticket').textContent=money(z.t);if($('vgvCasal'))$('vgvCasal').textContent=money(a.length?z.v/a.length:0);if($('count'))$('count').textContent=num(a.length)+' registros';if($('vgvProg'))$('vgvProg').style.width=Math.min(100,z.v/20000000*100)+'%';
if($('alerts'))$('alerts').innerHTML=z.conv<20?'<div class="alert">⚠️ <b>Conversão abaixo de 20%.</b> Revise abordagem e qualificação.</div>':'<div class="info">✅ Conversão atual: <b>'+pct(z.conv)+'</b></div>';
let f='<div class="funnelrow"><div class="funnelbar">ABORDAGENS</div><div class="ftxt">'+num(a.length)+'</div></div><div class="funnelrow"><div class="funnelbar q">QUALIFICADOS</div><div class="ftxt">'+num(z.q)+'</div></div><div class="funnelrow"><div class="funnelbar s">VENDAS</div><div class="ftxt">'+num(z.s.length)+'</div></div>';if($('funnel'))$('funnel').innerHTML=f;if($('funnel2'))$('funnel2').innerHTML=f}
function renderTeam(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv);let h=['#','PROMOTOR','ATENDIMENTOS','Q','NQ','VENDAS','CONVERSÃO','VGV','TICKET'];let html=table(r,h,(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td><td>'+money(x.vendas?x.vgv/x.vendas:0)+'</td></tr>');if($('teamTable'))$('teamTable').innerHTML=html}
function renderRank(a){let mode=document.querySelector('.tab.active')?.dataset.rank||'vgv';let r=rowsBy('Promotor de marketing',a);r=r.filter(x=>x.casais);if(mode==='vendas')r.sort((x,y)=>y.vendas-x.vendas||y.vgv-x.vgv);else if(mode==='conv')r.sort((x,y)=>(y.vendas/y.casais)-(x.vendas/x.casais)||y.vgv-x.vgv);else if(mode==='casais')r.sort((x,y)=>y.casais-x.casais);else r.sort((x,y)=>y.vgv-x.vgv);let html=table(r,['#','PROMOTOR','VGV','VENDAS','CONVERSÃO','ATENDIMENTOS'],(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td class="money">'+money(x.vgv)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td>'+num(x.casais)+'</td></tr>');if($('rankingTable'))$('rankingTable').innerHTML=html;if($('rankingFull'))$('rankingFull').innerHTML=html}
function renderOperation(a){let loc=rowsBy('Local Captação',a).sort((x,y)=>y.vgv-x.vgv);if($('locations'))$('locations').innerHTML=table(loc,['LOCAL','ATEND.','Q','NQ','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td></tr>');drawBars('hours',a,'_hour','Hora')}
function renderProfile(a){let cities=rowsBy('Cidade',a).sort((x,y)=>y.casais-x.casais);let prof1=rowsBy('Profissão 1',a),prof2=rowsBy('Profissão 2',a);let pm=new Map();[...prof1,...prof2].forEach(x=>{let o=pm.get(x.name)||{name:x.name,casais:0,vendas:0,vgv:0};o.casais+=x.casais;o.vendas+=x.vendas;o.vgv+=x.vgv;pm.set(x.name,o)});let prof=[...pm.values()].sort((x,y)=>y.casais-x.casais);if($('profileTable'))$('profileTable').innerHTML=table(cities,['CIDADE','ATENDIMENTOS','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td></tr>');if($('profile'))$('profile').innerHTML=table(prof,['PROFISSÃO','ATENDIMENTOS','VENDAS','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderAlerts(a){let r=rowsBy('Promotor de marketing',a).filter(x=>x.casais>=5).sort((x,y)=>(x.vendas/x.casais)-(y.vendas/y.casais));if($('alertList'))$('alertList').innerHTML=table(r.slice(0,15),['PROMOTOR','ATEND.','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="bad">'+pct(x.vendas/x.casais*100)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderData(a){let target=$('dataTable')||$('dadosTable')||$('rawTable');if(!target)return;let keys=['Data de atendimento','Promotor de marketing','Liner','Closer','Local Captação','Qualificação','Valor vendido'];target.innerHTML=table(a.slice(0,500),keys,x=>'<tr>'+keys.map(k=>'<td>'+((k==='Valor vendido')?money(x._v):(x[k]??''))+'</td>').join('')+'</tr>')+'<div class="ksub">Exibindo até 500 registros para manter o painel rápido. Total filtrado: '+num(a.length)+'</div>'}
function drawBars(id,a,key,label){const c=$(id);if(!c)return;const box=c.parentElement;const d={};a.forEach(x=>{let k=x[key]||'Não inf.';if(!d[k])d[k]={n:0,v:0};d[k].n++;d[k].v+=x._v});let arr=Object.entries(d).sort((x,y)=>y[1].v-x[1].v).slice(0,12);const ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.clearRect(0,0,w,h);ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=c.clientHeight,max=Math.max(...arr.map(x=>x[1].v),1);ctx.font='10px sans-serif';arr.forEach((x,i)=>{let y=18+i*(H-25)/Math.max(arr.length,1);let bw=(W-100)*x[1].v/max;ctx.fillStyle='#1683ff';ctx.fillRect(65,y,bw,12);ctx.fillStyle='#aab4c2';ctx.fillText(String(x[0]).slice(0,10),2,y+10);ctx.fillText(money(x[1].v),70+bw,y+10)})}
function renderDaily(a){const c=$('daily');if(!c)return;const d={};a.forEach(x=>{if(!x._date)return;if(!d[x._date])d[x._date]={v:0,n:0};d[x._date].v+=x._v;if(x._v>0)d[x._date].n++});const arr=Object.entries(d).sort();const ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight,D=devicePixelRatio;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);ctx.clearRect(0,0,W,H);if(!arr.length)return;const max=Math.max(...arr.map(x=>x[1].v),1);ctx.strokeStyle='#1683ff';ctx.lineWidth=2;ctx.beginPath();arr.forEach((x,i)=>{let px=35+i*(W-55)/Math.max(arr.length-1,1),py=H-25-(x[1].v/max)*(H-45);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#8d99aa';ctx.font='9px sans-serif';ctx.fillText('VGV por dia',5,12)}
function renderHighlights(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv)[0];if($('highlight'))$('highlight').innerHTML=r?'<div class="person"><div class="avatar">'+r.name.slice(0,1)+'</div><div><b>'+r.name+'</b><div class="badge">DESTAQUE</div></div></div><div class="stats"><div class="stat"><span>VGV</span><b>'+money(r.vgv)+'</b></div><div class="stat"><span>Vendas</span><b>'+num(r.vendas)+'</b></div><div class="stat"><span>Conversão</span><b>'+pct(r.casais?r.vendas/r.casais*100:0)+'</b></div><div class="stat"><span>Atend.</span><b>'+num(r.casais)+'</b></div></div>':'<div class="empty">Sem dados.</div>'}
function renderInsights(a){let z=baseStats(a),best=rowsBy('Promotor de marketing',a).filter(x=>x.casais>=5).sort((x,y)=>(y.vendas/y.casais)-(x.vendas/x.casais))[0];if($('insights'))$('insights').innerHTML='<div class="insight"><b>Leitura automática</b><p>'+num(z.a.length)+' atendimentos, '+num(z.q)+' qualificados e '+num(z.s.length)+' vendas, gerando '+money(z.v)+' de VGV.</p></div>'+(best?'<div class="insight"><b>Melhor conversão</b><p>'+best.name+' está em '+pct(best.vendas/best.casais*100)+' com '+num(best.casais)+' atendimentos.</p></div>':'')}
function renderMotives(a){let m=new Map();a.forEach(x=>{let k=String(x['Motivo de qualificação']||'Não informado').trim()||'Não informado';m.set(k,(m.get(k)||0)+1)});let rows=[...m.entries()].sort((x,y)=>y[1]-x[1]);if($('motives'))$('motives').innerHTML=table(rows.map(x=>({name:x[0],n:x[1]})),['MOTIVO','QUANTIDADE'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.n)+'</td></tr>')}
function renderQual(a){drawBars('qual',a,'Qualificação','Qualificação')}
function render(){let a=filtered();renderKPIs(a);renderTeam(a);renderRank(a);renderOperation(a);renderProfile(a);renderAlerts(a);renderData(a);renderDaily(a);renderHighlights(a);renderInsights(a);renderMotives(a);renderQual(a)}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>{b.onclick=function(){let p=this.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('main>section').forEach(x=>x.hidden=x.id!=='page-'+p);if($('pageTitle'))$('pageTitle').textContent={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados'}[p]||'FluxoHub';render()}})}
function actions(){document.querySelectorAll('[data-rank]').forEach(b=>b.onclick=function(){document.querySelectorAll('[data-rank]').forEach(x=>x.classList.toggle('active',x===b));renderRank(filtered())});if($('reset'))$('reset').onclick=function(){['promotor','liner','closer','local'].forEach(id=>{if($(id))$(id).value=''});let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';render()};if($('export'))$('export').onclick=function(){let a=filtered();let keys=['Data de atendimento','Promotor de marketing','Liner','Closer','Local Captação','Qualificação','Valor vendido'];let csv=[keys.join(';'),...a.map(x=>keys.map(k=>'"'+String(k==='Valor vendido'?x._v:(x[k]??'')).replace(/"/g,'""')+'"').join(';'))].join('\n');let blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=u;ael.download='fluxohub-export.csv';ael.click();URL.revokeObjectURL(u)};if($('importBtn')&&$('file')){$('importBtn').onclick=()=>$('file').click();$('file').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let lines=String(r.result).split(/\r?\n/).filter(Boolean);if(lines.length<2)return;let sep=lines[0].includes(';')?';':',';let heads=lines[0].split(sep).map(x=>x.replace(/^"|"$/g,''));let out=lines.slice(1).map(line=>{let c=line.split(sep);let o={};heads.forEach((h,i)=>o[h]=String(c[i]??'').replace(/^"|"$/g,''));return prep(o)});data=dedupe(out);fill('promotor','Promotor de marketing');fill('liner','Liner');fill('closer','Closer');fill('local','Local Captação');render()};r.readAsText(f,'UTF-8')}}}
function start(){nav();actions();['promotor','liner','closer','local','start','end'].forEach(id=>{let e=$(id);if(e)e.addEventListener('change',render)});render()}
fetch('./data.json?fluxohub='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('data.json '+r.status);return r.json()}).then(j=>{data=dedupe((Array.isArray(j)?j:(j.data||j.rows||[])).map(prep));let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';fill('promotor','Promotor de marketing');fill('liner','Liner');fill('closer','Closer');start()}).catch(e=>{console.error(e);if($('alerts'))$('alerts').innerHTML='<div class="alert"><b>Erro ao carregar a base.</b> '+e.message+'</div>';nav()});
})();
