(function(){'use strict';
const $=id=>document.getElementById(id);let data=[];
const OFFICIAL_VGV=61700089.96;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const num=v=>new Intl.NumberFormat('pt-BR').format(Number(v)||0);
const pct=v=>(Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
function val(v){if(v==null||v==='')return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v).trim().replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s.replace(/[^0-9.-]/g,''))||0}
function date(v){let s=String(v||'').trim(),m=s.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:/^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):''}
function clean(s){return String(s??'').trim().replace(/\s+/g,' ').toUpperCase()}
function prep(r){return Object.assign({},r,{_date:date(r['Data de atendimento']),_v:val(r['Valor vendido']),_q:clean(r['Qualificação']),_hour:(String(r['Data/Hora do cadastro']||'').match(/\s(\d{1,2}):/)||[])[1]||''})}
function dedupe(rows){const seen=new Set();return rows.filter(x=>{const k=[x['Data/Hora do cadastro'],x['Promotor de marketing'],x['Nome 1'],x['Nome 2'],x['Valor vendido'],x['Data de atendimento']].map(clean).join('|');if(seen.has(k))return false;seen.add(k);return true})}
function filtered(){let a=$('start')?.value,b=$('end')?.value,p=$('promotor')?.value,l=$('liner')?.value,c=$('closer')?.value,lo=$('local')?.value;return data.filter(x=>(!a||x._date>=a)&&(!b||x._date<=b)&&(!p||x['Promotor de marketing']===p)&&(!l||x.Liner===l)&&(!c||x.Closer===c)&&(!lo||x['Local Captação']===lo))}
function fill(id,key){let e=$(id);if(!e)return;let values=[...new Set(data.map(x=>String(x[key]??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));e.innerHTML='<option value="">Todos</option>';values.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;e.appendChild(o)})}
function rowsBy(key,a){let m=new Map();a.forEach(x=>{let k=String(x[key]||'Não informado').trim()||'Não informado',o=m.get(k)||{name:k,casais:0,vendas:0,vgv:0,q:0,nq:0};o.casais++;o.vgv+=x._v;if(x._v>0)o.vendas++;if(x._q==='Q'||x._q.startsWith('Q '))o.q++;if(x._q==='NQ'||x._q.startsWith('NQ'))o.nq++;m.set(k,o)});return [...m.values()]}
function table(rows,headers,render){if(!rows.length)return '<div class="empty">Nenhum registro no período/filtro selecionado.</div>';return '<div class="tablewrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(render).join('')+'</tbody></table></div>'}
function baseStats(a){let s=a.filter(x=>x._v>0),v=s.reduce((t,x)=>t+x._v,0);return{a,s,v,conv:a.length?s.length/a.length*100:0,t:s.length?v/s.length:0,q:a.filter(x=>x._q==='Q'||x._q.startsWith('Q ')).length,nq:a.filter(x=>x._q==='NQ'||x._q.startsWith('NQ')).length}}
function renderVgvCheck(v){let diff=v-OFFICIAL_VGV,ok=Math.abs(diff)<=.01,e=$('vgvCheck');if(!e){e=document.createElement('div');e.id='vgvCheck';let g=document.querySelector('#page-visao .grid');if(g)g.insertBefore(e,g.firstChild)}if(e){e.className=ok?'info':'alert';e.innerHTML=ok?'✓ <b>VGV CONFERIDO</b> · '+money(v):'⚠️ <b>Divergência de VGV</b> · Sistema: '+money(v)+' · Oficial: '+money(OFFICIAL_VGV)+' · Diferença: '+money(Math.abs(diff))}}
function renderKPIs(a){let z=baseStats(a);renderVgvCheck(z.v);if($('vgv'))$('vgv').textContent=money(z.v);if($('vgvSub'))$('vgvSub').textContent=num(z.s.length)+' vendas · '+pct(z.conv)+' conversão';if($('casais'))$('casais').textContent=num(a.length);if($('vendas'))$('vendas').textContent=num(z.s.length);if($('conv'))$('conv').textContent=pct(z.conv);if($('convSub'))$('convSub').textContent='Q: '+num(z.q)+' · NQ: '+num(z.nq);if($('ticket'))$('ticket').textContent=money(z.t);if($('vgvCasal'))$('vgvCasal').textContent=money(a.length?z.v/a.length:0);if($('alerts'))$('alerts').innerHTML=z.conv<20?'<div class="alert">⚠️ <b>Conversão abaixo de 20%.</b> Revise abordagem e qualificação.</div>':'<div class="info">✓ Conversão atual: <b>'+pct(z.conv)+'</b></div>';let f='<div class="funnelrow"><div class="funnelbar">ABORDAGENS</div><div class="ftxt">'+num(a.length)+'</div></div><div class="funnelrow"><div class="funnelbar q">QUALIFICADOS</div><div class="ftxt">'+num(z.q)+'</div></div><div class="funnelrow"><div class="funnelbar s">VENDAS</div><div class="ftxt">'+num(z.s.length)+'</div></div>';if($('funnel'))$('funnel').innerHTML=f;if($('funnel2'))$('funnel2').innerHTML=f}
function renderTeam(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv);if($('teamTable'))$('teamTable').innerHTML=table(r,['#','PROMOTOR','ATENDIMENTOS','Q','NQ','VENDAS','CONVERSÃO','VGV','TICKET'],(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td><td>'+money(x.vendas?x.vgv/x.vendas:0)+'</td></tr>')}
function renderRank(a){let mode=document.querySelector('.tab.active')?.dataset.rank||'vgv',r=rowsBy('Promotor de marketing',a);if(mode==='vendas')r.sort((x,y)=>y.vendas-x.vendas||y.vgv-x.vgv);else if(mode==='conv')r.sort((x,y)=>(y.vendas/y.casais)-(x.vendas/x.casais)||y.vgv-x.vgv);else if(mode==='casais')r.sort((x,y)=>y.casais-x.casais);else r.sort((x,y)=>y.vgv-x.vgv);let html=table(r,['#','PROMOTOR','VGV','VENDAS','CONVERSÃO','ATENDIMENTOS'],(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td class="money">'+money(x.vgv)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td>'+num(x.casais)+'</td></tr>');if($('rankingTable'))$('rankingTable').innerHTML=html;if($('rankingFull'))$('rankingFull').innerHTML=html}
function drawBars(id,a,key){let c=$(id);if(!c)return;let d={};a.forEach(x=>{let k=x[key]||'Não inf.';d[k]=(d[k]||0)+x._v});let arr=Object.entries(d).sort((x,y)=>y[1]-x[1]).slice(0,12),ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight,D=devicePixelRatio;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);ctx.clearRect(0,0,W,H);let max=Math.max(...arr.map(x=>x[1]),1);ctx.font='10px sans-serif';arr.forEach((x,i)=>{let y=18+i*(H-25)/Math.max(arr.length,1),bw=(W-100)*x[1]/max;ctx.fillStyle='#1683ff';ctx.fillRect(65,y,bw,12);ctx.fillStyle='#aab4c2';ctx.fillText(String(x[0]).slice(0,10),2,y+10);ctx.fillText(money(x[1]),70+bw,y+10)})}
function renderOperation(a){let loc=rowsBy('Local Captação',a).sort((x,y)=>y.vgv-x.vgv);if($('locations'))$('locations').innerHTML=table(loc,['LOCAL','ATEND.','Q','NQ','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td></tr>');drawBars('hours',a,'_hour')}
function renderProfile(a){let cities=rowsBy('Cidade',a).sort((x,y)=>y.casais-x.casais);if($('profileTable'))$('profileTable').innerHTML=table(cities,['CIDADE','ATENDIMENTOS','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td>'+pct(x.casais?x.vendas/x.casais*100:0)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderAlerts(a){let r=rowsBy('Promotor de marketing',a).filter(x=>x.casais>=5).sort((x,y)=>(x.vendas/x.casais)-(y.vendas/y.casais));if($('alertList'))$('alertList').innerHTML=table(r.slice(0,15),['PROMOTOR','ATEND.','VENDAS','CONVERSÃO','VGV'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.casais)+'</td><td>'+num(x.vendas)+'</td><td class="bad">'+pct(x.vendas/x.casais*100)+'</td><td class="money">'+money(x.vgv)+'</td></tr>')}
function renderData(a){let target=$('dataTable')||$('dadosTable')||$('rawTable');if(!target)return;let keys=['Data de atendimento','Promotor de marketing','Liner','Closer','Local Captação','Qualificação','Valor vendido'];target.innerHTML=table(a.slice(0,500),keys,x=>'<tr>'+keys.map(k=>'<td>'+((k==='Valor vendido')?money(x._v):(x[k]??''))+'</td>').join('')+'</tr>')+'<div class="ksub">Exibindo até 500 registros. Total filtrado: '+num(a.length)+'</div>'}
function renderDaily(a){let c=$('daily');if(!c)return;let d={};a.forEach(x=>{if(x._date){d[x._date]=d[x._date]||0;d[x._date]+=x._v}});let arr=Object.entries(d).sort(),ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight,D=devicePixelRatio;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);ctx.clearRect(0,0,W,H);let max=Math.max(...arr.map(x=>x[1]),1);ctx.strokeStyle='#1683ff';ctx.lineWidth=2;ctx.beginPath();arr.forEach((x,i)=>{let px=35+i*(W-55)/Math.max(arr.length-1,1),py=H-25-x[1]/max*(H-45);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke()}
function renderHighlights(a){let r=rowsBy('Promotor de marketing',a).sort((x,y)=>y.vgv-x.vgv)[0];if($('highlight'))$('highlight').innerHTML=r?'<div class="person"><div class="avatar">'+r.name.slice(0,1)+'</div><div><b>'+r.name+'</b><div class="badge">DESTAQUE</div></div></div><div class="stats"><div class="stat"><span>VGV</span><b>'+money(r.vgv)+'</b></div><div class="stat"><span>Vendas</span><b>'+num(r.vendas)+'</b></div><div class="stat"><span>Conversão</span><b>'+pct(r.casais?r.vendas/r.casais*100:0)+'</b></div><div class="stat"><span>Atend.</span><b>'+num(r.casais)+'</b></div></div>':'<div class="empty">Sem dados.</div>'}
function renderInsights(a){let z=baseStats(a);if($('insights'))$('insights').innerHTML='<div class="insight"><b>Leitura automática</b><p>'+num(z.a.length)+' atendimentos, '+num(z.q)+' qualificados e '+num(z.s.length)+' vendas, gerando '+money(z.v)+' de VGV.</p></div>'}
function renderMotives(a){let m=new Map();a.forEach(x=>{let k=String(x['Motivo de qualificação']||'Não informado').trim()||'Não informado';m.set(k,(m.get(k)||0)+1)});if($('motives'))$('motives').innerHTML=table([...m.entries()].sort((x,y)=>y[1]-x[1]).map(x=>({name:x[0],n:x[1]})),['MOTIVO','QUANTIDADE'],x=>'<tr><td>'+x.name+'</td><td>'+num(x.n)+'</td></tr>')}
function render(){let a=filtered();renderKPIs(a);renderTeam(a);renderRank(a);renderOperation(a);renderProfile(a);renderAlerts(a);renderData(a);renderDaily(a);renderHighlights(a);renderInsights(a);renderMotives(a);renderXP()}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=function(){let p=this.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('main>section').forEach(x=>x.hidden=x.id!=='page-'+p);if($('pageTitle'))$('pageTitle').textContent={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados',xp:'XP BMW GAME'}[p]||'FluxoHub';if(p==='xp')renderXP();render()})}
function actions(){document.querySelectorAll('[data-rank]').forEach(b=>b.onclick=function(){document.querySelectorAll('[data-rank]').forEach(x=>x.classList.toggle('active',x===b));renderRank(filtered())});if($('reset'))$('reset').onclick=function(){['promotor','liner','closer','local'].forEach(id=>{if($(id))$(id).value=''});let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';render()};if($('export'))$('export').onclick=function(){let a=filtered(),keys=['Data de atendimento','Promotor de marketing','Liner','Closer','Local Captação','Qualificação','Valor vendido'],csv=[keys.join(';'),...a.map(x=>keys.map(k=>'"'+String(k==='Valor vendido'?x._v:(x[k]??'')).replace(/"/g,'""')+'"').join(';'))].join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=u;ael.download='fluxohub-export.csv';ael.click();URL.revokeObjectURL(u)}}
function setupXP(){if(document.getElementById('xpNav'))return;let nav=document.querySelector('.nav'),main=document.querySelector('main');if(!nav||!main)return;let b=document.createElement('button');b.id='xpNav';b.dataset.page='xp';b.innerHTML='<span>🏆</span>XP BMW GAME';nav.appendChild(b);let s=document.createElement('section');s.id='page-xp';s.hidden=true;s.innerHTML='<div class="grid"><div class="card s12"><div class="title">🏆 XP BMW GAME — BMW X1 2012</div><div class="subtitle">Campanha iniciada em 01/07/2026 · o dia 01/07/2026 está incluído na base válida do ranking.</div><div class="metricgrid"><div class="metricbox"><span>VIGÊNCIA</span><strong>01/07/2026</strong></div><div class="metricbox"><span>REGRA</span><strong>Maior XP acumulado</strong></div><div class="metricbox"><span>PROMOTOR</span><strong>Regras pendentes</strong></div></div><div id="xpRules" style="margin-top:14px"></div></div><div class="card s12"><div class="title">Ranking XP — resultado válido a partir de 01/07/2026</div><div id="xpRanking"></div></div></div>';main.appendChild(s)}
function roleRows(role,a){let key=role==='Captador'?'Promotor de marketing':role==='Liner'?'Liner':'Closer',rate=role==='Captador'?1.4:role==='Liner'?1.2:1,group=new Map();a.filter(x=>x._date>='2026-07-01').forEach(x=>{let name=String(x[key]||'').trim();if(!name)return;let o=group.get(name)||{name,vgv:0,vendas:0,days:new Set()};o.vgv+=x._v;o.vendas+=x._v>0?1:0;o.days.add(x._date);group.set(name,o)});return [...group.values()].map(o=>{let xp=o.vgv/1000*rate*1000;return{...o,xp,role}}).sort((a,b)=>b.xp-a.xp)}
function renderXP(){setupXP();let root=$('xpRanking'),rules=$('xpRules');if(!root)return;let a=data.filter(x=>x._date>='2026-07-01');let all=[...roleRows('Captador',a),...roleRows('Liner',a),...roleRows('Closer',a)].sort((x,y)=>y.xp-x.xp);let rows=all.map((x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td>'+x.role+'</td><td class="money">'+money(x.vgv)+'</td><td>'+num(x.vendas)+'</td><td>'+num(x.days.size)+'</td><td><b>'+num(Math.round(x.xp))+' XP</b></td></tr>');root.innerHTML=table(all,['#','PROFISSIONAL','CARGO','VGV','VENDAS','DIAS COM REGISTRO','XP'],(x,i)=>'<tr><td class="ranknum">'+(i+1)+'</td><td>'+x.name+'</td><td>'+x.role+'</td><td class="money">'+money(x.vgv)+'</td><td>'+num(x.vendas)+'</td><td>'+num(x.days.size)+'</td><td><b>'+num(Math.round(x.xp))+' XP</b></td></tr>');if(rules)rules.innerHTML='<div class="tablewrap"><table><thead><tr><th>CARGO</th><th>VGV POR R$1.000</th><th>PRESENÇA/DIA</th><th>PONTUALIDADE/DIA</th><th>TOP MÊS</th><th>TICKET MÉDIO</th><th>BÔNUS MÁX.</th></tr></thead><tbody><tr><td>Captador</td><td>1.400 XP</td><td>50.000 XP</td><td>50.000 XP</td><td>450k / 300k / 100k</td><td>300k / 200k / 100k</td><td>2.400.000 XP</td></tr><tr><td>Liner / Consultoria</td><td>1.200 XP</td><td>50.000 XP</td><td>50.000 XP</td><td>600k / 400k / 200k</td><td>300k / 200k / 100k</td><td>2.400.000 XP</td></tr><tr><td>Closer</td><td>1.000 XP</td><td>50.000 XP</td><td>50.000 XP</td><td>600k / 400k / 200k</td><td>300k / 200k / 100k</td><td>2.400.000 XP</td></tr><tr><td>Promotor</td><td colspan="6">⚠️ REGRAS DO PROMOTOR — PENDENTE DE DEFINIÇÃO. Nenhuma pontuação foi inventada.</td></tr></tbody></table></div><div class="info" style="margin-top:10px"><b>Regra do ranking:</b> maior XP acumulado vence. O XP acima usa somente o VGV registrado a partir de 01/07/2026. Presença, pontualidade, TOP, ticket e bônus só entram quando houver dados válidos para esses eventos; o sistema não inventa esses pontos.</div>'}
function start(){setupXP();nav();actions();['promotor','liner','closer','local','start','end'].forEach(id=>{let e=$(id);if(e)e.addEventListener('change',render)});render()}
fetch('./data.json?fluxohub='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('data.json '+r.status);return r.json()}).then(j=>{data=dedupe((Array.isArray(j)?j:(j.data||j.rows||[])).map(prep));let ds=data.map(x=>x._date).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';fill('promotor','Promotor de marketing');fill('liner','Liner');fill('closer','Closer');fill('local','Local Captação');start()}).catch(e=>{console.error(e);if($('alerts'))$('alerts').innerHTML='<div class="alert"><b>Erro ao carregar a base.</b> '+e.message+'</div>';nav()});
})();