(()=>{'use strict';
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);const num=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);const pct=n=>`${((Number(n)||0)*100).toFixed(1).replace('.',',')}%`;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let rows=[],metric='casais';
function unpack(p){if(!(p&&Array.isArray(p.d)&&Array.isArray(p.r)))return[];const[P,,,,Q]=p.d;return p.r.map(a=>({date:a[0],promotor:String(P[a[1]]||'').trim(),q:String(Q[a[6]]||''),sales:+a[7]||0,activeV:+a[8]||0})).filter(r=>r.promotor&&r.date)}
function active(n){return typeof window.CAPTAUP_IS_ACTIVE==='function'?window.CAPTAUP_IS_ACTIVE(n):n!=='Não informado'}
function grouped(){const st=$('start')?.value||'',en=$('end')?.value||'',sel=$('promotor')?.value||'';const m=new Map();for(const r of rows){if((st&&r.date<st)||(en&&r.date>en)||(sel&&r.promotor!==sel)||!active(r.promotor))continue;const k=r.promotor;if(!m.has(k))m.set(k,{name:k,casais:0,activeV:0,sales:0,q:0,nq:0});const x=m.get(k);x.casais++;x.activeV+=r.activeV;x.sales+=r.sales;if(r.q.toUpperCase()==='Q')x.q++;else if(r.q.toUpperCase()==='NQ')x.nq++;}return[...m.values()].map(x=>({...x,conv:x.casais?x.sales/x.casais:0,vgvCasal:x.casais?x.activeV/x.casais:0})).sort((a,b)=>b[metric]-a[metric]||b.casais-a.casais||b.activeV-a.activeV)}
function ensure(){const page=$('page-visao');if(!page)return null;let box=$('promotorFocus');if(box)return box;box=document.createElement('div');box.id='promotorFocus';box.className='card';box.style.cssText='margin:14px 0;border:1px solid #2677b8;box-shadow:0 18px 55px #0008';box.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-end;flex-wrap:wrap"><div><div class="klabel">FOCO DA VISÃO 360°</div><div class="title" style="font-size:20px">Ranking dos Promotores</div><div class="subtitle">Equipe ativa no período selecionado</div></div><div class="tabs" id="promotorFocusTabs"><button class="tab active" data-pf="casais">Casais</button><button class="tab" data-pf="activeV">VGV líquido</button><button class="tab" data-pf="sales">Vendas</button><button class="tab" data-pf="conv">Conversão</button></div></div><div id="promotorFocusTable" style="margin-top:12px"></div>';const k=page.querySelector('.kpis');k?.insertAdjacentElement('afterend',box);box.querySelectorAll('[data-pf]').forEach(b=>b.onclick=()=>{metric=b.dataset.pf;box.querySelectorAll('[data-pf]').forEach(x=>x.classList.toggle('active',x===b));render()});return box}
function render(){ensure();const host=$('promotorFocusTable');if(!host)return;const gs=grouped();host.innerHTML=gs.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>Promotor</th><th>Casais</th><th>VGV líquido</th><th>Vendas</th><th>Conversão</th><th>Q/NQ</th><th>VGV/Casal</th></tr></thead><tbody>${gs.map((g,i)=>`<tr><td><b>${i+1}º</b></td><td><b>${esc(g.name)}</b></td><td>${num(g.casais)}</td><td class="money">${money(g.activeV)}</td><td>${num(g.sales)}</td><td>${pct(g.conv)}</td><td>${g.q}/${g.nq}</td><td>${money(g.vgvCasal)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="info">Nenhum promotor ativo encontrado neste período.</div>'}
async function init(){ensure();if(typeof window.loadCaptaUpAnnual!=='function'){setTimeout(init,150);return}try{rows=unpack(await window.loadCaptaUpAnnual());render()}catch(e){const h=$('promotorFocusTable');if(h)h.innerHTML='<div class="info">Não foi possível carregar o ranking dos promotores.</div>';console.warn('promotor-focus',e)}['start','end','promotor'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(render,20)));$('reset')?.addEventListener('click',()=>setTimeout(render,40));setTimeout(render,500);setTimeout(render,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();