(function(){
'use strict';
var OFFICIAL_VGV=61700089.96, DATA=[];
var $=function(id){return document.getElementById(id)};
var money=function(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)};
var num=function(v){return new Intl.NumberFormat('pt-BR').format(Number(v)||0)};
var pct=function(v){return (Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%'};
function val(v){if(v==null||v==='')return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;var s=String(v).trim().replace(/R\$/gi,'').replace(/\s/g,'');if(s.indexOf(',')>=0&&s.indexOf('.')>=0)s=s.replace(/\./g,'').replace(',','.');else if(s.indexOf(',')>=0)s=s.replace(',','.');return Number(s.replace(/[^0-9.-]/g,''))||0}
function date(v){var s=String(v||'').trim(),m=s.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:(/^\d{4}-\d{2}-\d{2}/.test(s)?s.slice(0,10):'')}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function prep(r){r=Object.assign({},r);r._date=date(r['Data de atendimento']||r['Data']);r._v=val(r['Valor vendido']||r['VGV']||r['Valor']);r._q=String(r['Qualificação']||r['Qualificacao']||'').trim().toUpperCase();return r}
function filtered(){var a=$('start')&&$('start').value,b=$('end')&&$('end').value,p=$('promotor')&&$('promotor').value,l=$('liner')&&$('liner').value,c=$('closer')&&$('closer').value,o=$('local')&&$('local').value;return DATA.filter(function(x){return(!a||!x._date||x._date>=a)&&(!b||!x._date||x._date<=b)&&(!p||String(x['Promotor de marketing']||'').trim()===p)&&(!l||String(x.Liner||'').trim()===l)&&(!c||String(x.Closer||'').trim()===c)&&(!o||String(x['Local Captação']||'').trim()===o)})}
function fill(id,key){var e=$(id);if(!e)return;var vals={};DATA.forEach(function(x){var v=String(x[key]||'').trim();if(v)vals[v]=1});e.innerHTML='<option value="">Todos</option>'+Object.keys(vals).sort(function(a,b){return a.localeCompare(b,'pt-BR')}).map(function(v){return '<option value="'+esc(v)+'">'+esc(v)+'</option>'}).join('')}
function groups(a,key){var m={};a.forEach(function(x){var k=String(x[key]||'Não informado').trim()||'Não informado';if(!m[k])m[k]={name:k,a:0,s:0,v:0,q:0,nq:0};m[k].a++;m[k].v+=x._v;if(x._v>0)m[k].s++;if(x._q==='Q'||x._q.indexOf('Q ')===0)m[k].q++;if(x._q==='NQ'||x._q.indexOf('NQ')===0)m[k].nq++});return Object.keys(m).map(function(k){var x=m[k];x.conv=x.a?x.s/x.a*100:0;x.ticket=x.s?x.v/x.s:0;return x})}
function table(rows,headers,render){if(!rows.length)return '<div class="empty">Nenhum registro no período/filtro selecionado.</div>';return '<div class="tablewrap"><table><thead><tr>'+headers.map(function(h){return '<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(render).join('')+'</tbody></table></div>'}
function cleanBlockers(){document.querySelectorAll('[data-fluxohub-blocker],.click-blocker,.interaction-blocker').forEach(function(e){e.remove()});document.querySelectorAll('body>*').forEach(function(e){if(e.classList&&e.classList.contains('app'))return;var s=getComputedStyle(e);if((s.position==='fixed'||s.position==='absolute')&&s.display!=='none'&&s.visibility!=='hidden'&&Number(s.zIndex||0)>40){var r=e.getBoundingClientRect();if(r.width>innerWidth*.9&&r.height>innerHeight*.9&&!e.classList.contains('modal'))e.style.pointerEvents='none'}})}
function style(){if($('fluxohub-stable-style'))return;var s=document.createElement('style');s.id='fluxohub-stable-style';s.textContent='.nav button,.mobilebar button,.tab,.btn,.field,.field input,.field select{pointer-events:auto!important;position:relative;z-index:100!important}.nav,.actions,.filters{position:relative;z-index:100!important}.top{z-index:200!important}.mobilebar{z-index:200!important}.daily-card .chart{height:335px}@media(max-width:700px){.daily-card .chart{height:280px}}';document.head.appendChild(s)}
function render(){var a=filtered(),s=a.filter(function(x){return x._v>0}),v=s.reduce(function(t,x){return t+x._v},0),q=a.filter(function(x){return x._q==='Q'||x._q.indexOf('Q ')===0}).length,nq=a.filter(function(x){return x._q==='NQ'||x._q.indexOf('NQ')===0}).length,cv=a.length?s.length/a.length*100:0,t=s.length?v/s.length:0;
 if($('vgv'))$('vgv').textContent=money(v);if($('vgvSub'))$('vgvSub').textContent=num(s.length)+' vendas · '+pct(cv)+' conversão';if($('casais'))$('casais').textContent=num(a.length);if($('vendas'))$('vendas').textContent=num(s.length);if($('conv'))$('conv').textContent=pct(cv);if($('convSub'))$('convSub').textContent='Q: '+num(q)+' · NQ: '+num(nq);if($('ticket'))$('ticket').textContent=money(t);if($('vgvCasal'))$('vgvCasal').textContent=money(a.length?v/a.length:0);
 var check=$('vgvCheck');if(!check){check=document.createElement('div');check.id='vgvCheck';var card=$('vgv')&&$('vgv').closest('.card');if(card)card.appendChild(check)}var hasFilter=($('promotor')&&$('promotor').value)||($('liner')&&$('liner').value)||($('closer')&&$('closer').value)||($('local')&&$('local').value);if(check){check.className=hasFilter?'info':(Math.abs(v-OFFICIAL_VGV)<=.01?'info':'alert');check.innerHTML=hasFilter?'ℹ️ VGV do filtro atual: <b>'+money(v)+'</b>':'✓ VGV conferido · <b>'+money(v)+'</b> · Oficial: '+money(OFFICIAL_VGV)}
 var r=groups(a,'Promotor de marketing').sort(function(x,y){return y.v-x.v});var html=table(r,['#','PROMOTOR','VGV','VENDAS','CONVERSÃO','ATENDIMENTOS'],function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.name)+'</td><td class="money">'+money(x.v)+'</td><td>'+num(x.s)+'</td><td>'+pct(x.conv)+'</td><td>'+num(x.a)+'</td></tr>'});if($('rankingTable'))$('rankingTable').innerHTML=html;if($('rankingFull'))$('rankingFull').innerHTML=html;if($('teamTable'))$('teamTable').innerHTML=html;
 if($('alerts'))$('alerts').innerHTML=cv<20?'<div class="alert">⚠️ <b>Conversão abaixo de 20%.</b> Revise abordagem e qualificação.</div>':'<div class="info">✓ Conversão atual: <b>'+pct(cv)+'</b></div>';
 var funnel='<div class="funnelrow"><div class="funnelbar">ABORDAGENS</div><div class="ftxt">'+num(a.length)+'</div></div><div class="funnelrow"><div class="funnelbar q">QUALIFICADOS</div><div class="ftxt">'+num(q)+'</div></div><div class="funnelrow"><div class="funnelbar s">VENDAS</div><div class="ftxt">'+num(s.length)+'</div></div>';if($('funnel'))$('funnel').innerHTML=funnel;if($('funnel2'))$('funnel2').innerHTML=funnel;
 var cities=groups(a,'Cidade').sort(function(x,y){return y.a-x.a});if($('profileTable'))$('profileTable').innerHTML=table(cities,['CIDADE','ATEND.','VENDAS','CONVERSÃO','VGV'],function(x){return '<tr><td>'+esc(x.name)+'</td><td>'+num(x.a)+'</td><td>'+num(x.s)+'</td><td>'+pct(x.conv)+'</td><td class="money">'+money(x.v)+'</td></tr>'});
 if($('locations')){var loc=groups(a,'Local Captação').sort(function(x,y){return y.v-x.v});$('locations').innerHTML=table(loc,['LOCAL','ATEND.','Q','NQ','VENDAS','CONVERSÃO','VGV'],function(x){return '<tr><td>'+esc(x.name)+'</td><td>'+num(x.a)+'</td><td>'+num(x.q)+'</td><td>'+num(x.nq)+'</td><td>'+num(x.s)+'</td><td>'+pct(x.conv)+'</td><td class="money">'+money(x.v)+'</td></tr>'})}
 if($('alertList')){var ar=groups(a,'Promotor de marketing').filter(function(x){return x.a>=5}).sort(function(x,y){return x.conv-y.conv});$('alertList').innerHTML=table(ar.slice(0,15),['PROMOTOR','ATEND.','VENDAS','CONVERSÃO','VGV'],function(x){return '<tr><td>'+esc(x.name)+'</td><td>'+num(x.a)+'</td><td>'+num(x.s)+'</td><td class="bad">'+pct(x.conv)+'</td><td class="money">'+money(x.v)+'</td></tr>'})}
 if($('dataTable')){$('dataTable').innerHTML=table(a.slice(0,500),['DATA','PROMOTOR','CLIENTE','Q/NQ','VGV','LOCAL'],function(x){return '<tr><td>'+esc(x['Data de atendimento'])+'</td><td>'+esc(x['Promotor de marketing'])+'</td><td>'+esc(x['Nome 1'])+'</td><td>'+esc(x['Qualificação'])+'</td><td class="money">'+money(x._v)+'</td><td>'+esc(x['Local Captação'])+'</td></tr>'})+'<div class="ksub">Exibindo até 500 registros. Total filtrado: '+num(a.length)+'</div>'}
 if($('highlight')){var h=r[0];$('highlight').innerHTML=h?'<div class="person"><div class="avatar">'+esc(h.name.slice(0,1))+'</div><div><b>'+esc(h.name)+'</b><div class="badge">DESTAQUE</div></div></div><div class="stats"><div class="stat"><span>VGV</span><b>'+money(h.v)+'</b></div><div class="stat"><span>Vendas</span><b>'+num(h.s)+'</b></div><div class="stat"><span>Conversão</span><b>'+pct(h.conv)+'</b></div><div class="stat"><span>Atend.</span><b>'+num(h.a)+'</b></div></div>':'<div class="empty">Sem dados.</div>'}
 if($('insights'))$('insights').innerHTML='<div class="insight"><b>Leitura automática</b><p>'+num(a.length)+' atendimentos, '+num(q)+' qualificados e '+num(s.length)+' vendas, gerando '+money(v)+' de VGV.</p></div>';
 drawDaily(a);
}
function drawDaily(a){var c=$('daily');if(!c)return;var m={};a.forEach(function(x){if(x._date)m[x._date]=(m[x._date]||0)+x._v});var arr=Object.keys(m).sort().map(function(k){return[k,m[k]]});var ctx=c.getContext('2d'),W=c.clientWidth||700,H=c.clientHeight||335,D=window.devicePixelRatio||1;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);ctx.clearRect(0,0,W,H);if(!arr.length){ctx.fillStyle='#8d99aa';ctx.font='12px sans-serif';ctx.fillText('Sem dados para o período selecionado',20,30);return}var max=Math.max.apply(null,arr.map(function(x){return x[1]}))||1;ctx.strokeStyle='#1683ff';ctx.lineWidth=3;ctx.beginPath();arr.forEach(function(x,i){var px=30+i*(W-50)/Math.max(arr.length-1,1),py=H-30-(x[1]/max)*(H-60);if(i)ctx.lineTo(px,py);else ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#8d99aa';ctx.font='9px sans-serif';arr.forEach(function(x,i){if(i===0||i===arr.length-1){var px=30+i*(W-50)/Math.max(arr.length-1,1);ctx.fillText(x[0].slice(8),px-8,H-10)}})}
function navigation(){var titles={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados',xp:'XP BMW GAME'};document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-page]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();var p=b.dataset.page;document.querySelectorAll('[data-page]').forEach(function(x){x.classList.toggle('active',x.dataset.page===p)});document.querySelectorAll('main>section[id^="page-"]').forEach(function(s){s.hidden=s.id!=='page-'+p});if($('pageTitle'))$('pageTitle').textContent=titles[p]||'FluxoHub';render();window.scrollTo(0,0)},true)}
function controls(){['start','end','promotor','liner','closer','local'].forEach(function(id){var e=$(id);if(e)e.addEventListener('change',render)});if($('reset'))$('reset').addEventListener('click',function(){['promotor','liner','closer','local'].forEach(function(id){if($(id))$(id).value=''});var ds=DATA.map(function(x){return x._date}).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';render()})}
function install(){if($('installPwa'))return;var a=document.querySelector('.actions');if(!a)return;var b=document.createElement('button');b.id='installPwa';b.className='btn primary';b.textContent='📲 Instalar App';b.hidden=true;a.insertBefore(b,a.firstChild);var deferred=null;window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e;b.hidden=false});b.onclick=async function(){if(!deferred){alert('Abra o menu do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.');return}deferred.prompt();try{await deferred.userChoice}catch(e){}deferred=null;b.hidden=true}}
function errorBox(e){var old=$('fluxohub-error');if(old)return;var d=document.createElement('div');d.id='fluxohub-error';d.className='alert';d.style.cssText='position:fixed;left:10px;right:10px;bottom:10px;z-index:9999';d.innerHTML='<b>Erro ao carregar os dados.</b> Verifique se o data.json está publicado. <small>'+esc(e&&e.message||e)+'</small>';document.body.appendChild(d)}
async function load(){try{var r=await fetch('./data.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('data.json HTTP '+r.status);var j=await r.json();var raw=Array.isArray(j)?j:(j&&Array.isArray(j.data)?j.data:(j&&Array.isArray(j.rows)?j.rows:[]));if(!raw.length)throw Error('data.json sem registros reconhecidos');DATA=raw.map(prep);var ds=DATA.map(function(x){return x._date}).filter(Boolean).sort();if($('start'))$('start').value=ds[0]||'';if($('end'))$('end').value=ds[ds.length-1]||'';fill('promotor','Promotor de marketing');fill('liner','Liner');fill('closer','Closer');fill('local','Local Captação');render()}catch(e){console.error(e);errorBox(e)}}
function boot(){cleanBlockers();style();navigation();controls();install();load()}
window.addEventListener('error',function(e){console.error('FluxoHub JS',e.error||e.message)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();