(()=>{
'use strict';
const $=id=>document.getElementById(id);
const qs=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
const pct=n=>((Number(n)||0)*100).toFixed(1).replace('.',',')+'%';
const number=v=>{if(typeof v==='number')return isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/R\$|\s/g,'');if(s.includes('.')&&s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s.replace(/[^0-9.-]/g,''));return isFinite(n)?n:0};
const date=v=>{let s=String(v??'').trim(),m=s.match(/^(\d{2})[\/.-](\d{2})[\/.-](\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})[\/.-](\d{2})[\/.-](\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:''};
const val=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&o[k]!=='')return o[k];const nk=keys.map(norm);for(const k of Object.keys(o||{}))if(nk.includes(norm(k)))return o[k];return ''};
function prep(o){return{raw:o,date:date(val(o,['Data de atendimento','data','date'])),promotor:String(val(o,['Promotor de marketing','Promotor','promotor'])||'').trim(),liner:String(val(o,['Liner','liner'])||'').trim(),closer:String(val(o,['Closer','closer'])||'').trim(),local:String(val(o,['Local Captação','Local','local'])||'').trim(),vgv:number(val(o,['Valor vendido','VGV','vgv','valor_vendido'])),q:String(val(o,['Qualificação','Qualificacao','Q','q'])||'').trim(),city:String(val(o,['Cidade','CIDADE'])||'').trim(),profession:String(val(o,['Profissão','Profissao'])||'').trim(),income:String(val(o,['Renda','RENDA'])||'').trim(),hour:String(val(o,['Hora de atendimento','Horário','Horario'])||'').trim()};}
let rows=[];
function flat(x){if(Array.isArray(x))return x.flatMap(flat);if(x&&typeof x==='object'){const v=Object.values(x);if(v.length&&v.every(z=>z&&typeof z==='object'&&!Array.isArray(z)))return v.flatMap(flat);return[x]}return[]}
function fillSelect(id,field){const e=$(id);if(!e)return;const a=[...new Set(rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));e.innerHTML='<option value="">Todos</option>'+a.map(v=>`<option value="${String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}">${String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;')}</option>`).join('')}
function filters(){fillSelect('promotor','promotor');fillSelect('liner','liner');fillSelect('closer','closer');fillSelect('local','local');const ds=rows.map(r=>r.date).filter(Boolean).sort();if(ds.length){if($('start'))$('start').value=ds[0];if($('end'))$('end').value=ds.at(-1)}}
function filtered(){const st=$('start')?.value,en=$('end')?.value,p=$('promotor')?.value,l=$('liner')?.value,c=$('closer')?.value,lo=$('local')?.value;return rows.filter(r=>(!st||!r.date||r.date>=st)&&(!en||!r.date||r.date<=en)&&(!p||r.promotor===p)&&(!l||r.liner===l)&&(!c||r.closer===c)&&(!lo||r.local===lo))}
function agg(a){const v=a.reduce((s,r)=>s+r.vgv,0),sales=a.filter(r=>r.vgv>0).length;return{v,sales,atend:a.length,conv:a.length?sales/a.length:0,ticket:sales?v/sales:0,per:a.length?v/a.length:0}}
function render(){const a=filtered(),m=agg(a);if($('vgv'))$('vgv').textContent=money(m.v);if($('casais'))$('casais').textContent=num(m.atend);if($('vendas'))$('vendas').textContent=num(m.sales);if($('conv'))$('conv').textContent=pct(m.conv);if($('ticket'))$('ticket').textContent=money(m.ticket);if($('vgvCasal'))$('vgvCasal').textContent=money(m.per);if($('vgvSub'))$('vgvSub').textContent=`${num(m.sales)} vendas · ${pct(m.conv)} conversão`;if($('convSub'))$('convSub').textContent='vendas ÷ atendimentos';if($('vgvProg'))$('vgvProg').style.width=Math.min(100,m.v/61700089.96*100)+'%';const g=a.reduce((map,r)=>{const k=r.promotor||'Não informado';if(!map[k])map[k]=[];map[k].push(r);return map},{});const rank=Object.entries(g).map(([name,x])=>({name,m:agg(x)})).sort((x,y)=>y.m.v-x.m.v);if($('rankingTable'))$('rankingTable').innerHTML=rank.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>Promotor</th><th>VGV</th><th>Vendas</th><th>Conversão</th><th>Atendimentos</th></tr></thead><tbody>${rank.slice(0,30).map((x,i)=>`<tr><td>${i+1}</td><td>${x.name}</td><td class="money">${money(x.m.v)}</td><td>${num(x.m.sales)}</td><td>${pct(x.m.conv)}</td><td>${num(x.m.atend)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum registro encontrado.</div>';if($('highlight'))$('highlight').innerHTML=rank[0]?`<div class="person"><div class="avatar">${rank[0].name.slice(0,1).toUpperCase()}</div><div><b>${rank[0].name}</b><div class="badge">TOP VGV</div></div></div><div class="stats"><div class="stat">VGV <b>${money(rank[0].m.v)}</b></div><div class="stat">Vendas <b>${num(rank[0].m.sales)}</b></div><div class="stat">Conversão <b>${pct(rank[0].m.conv)}</b></div><div class="stat">Atendimentos <b>${num(rank[0].m.atend)}</b></div></div>`:'<div class="empty">Sem dados.</div>';if($('insights'))$('insights').innerHTML=`<div class="insight"><b>Resumo</b><p>${num(m.sales)} vendas em ${num(m.atend)} atendimentos, com conversão de ${pct(m.conv)} e VGV de ${money(m.v)}.</p></div><div class="info">Registros filtrados: <b>${num(a.length)}</b></div>`;if($('alerts'))$('alerts').innerHTML=m.conv<.2?'<div class="alert"><b>⚠️ Conversão abaixo de 20%.</b><p>Revise abordagem e qualificação.</p></div>':'<div class="info">✅ Conversão acima de 20%.</div>';qs('.section-filter').forEach(b=>['start','end','promotor','liner','closer','local'].forEach(id=>{const s=$(id),d=b.querySelector(`[data-filter="${id}"]`);if(s&&d){if(d.tagName==='SELECT')d.innerHTML=s.innerHTML;d.value=s.value||''}}));}
function nav(p){qs('main>section').forEach(s=>s.hidden=s.id!==`page-${p}`);qs('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if($('pageTitle'))$('pageTitle').textContent={visao:'Visão 360°',equipe:'Equipe',funil:'Funil de Vendas',ranking:'Ranking',operacao:'Operação',perfil:'Perfil do Cliente',alertas:'Alertas',dados:'Dados'}[p]||'FluxoHub';}
function addSectionFilters(){qs('section[id^="page-"]').forEach(s=>{if(s.querySelector('.section-filter'))return;const d=document.createElement('div');d.className='section-filter filters';d.innerHTML='<div class="field"><label>PERÍODO</label><input data-filter="start" type="date"></div><div class="field"><label>ATÉ</label><input data-filter="end" type="date"></div><div class="field"><label>PROMOTOR</label><select data-filter="promotor"></select></div><div class="field"><label>LINER</label><select data-filter="liner"></select></div><div class="field"><label>CLOSER</label><select data-filter="closer"></select></div><div class="field"><label>LOCAL</label><select data-filter="local"></select></div>';s.prepend(d);d.addEventListener('change',e=>{const id=e.target.dataset.filter;if(id&&$(id))$(id).value=e.target.value;render()})})}
async function load(){try{const r=await fetch('./data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);rows=flat(await r.json()).map(prep).filter(r=>r.promotor||r.vgv||r.date||r.local);filters();addSectionFilters();render()}catch(e){console.error('FluxoHub bootstrap',e);if($('vgv'))$('vgv').textContent='Erro';if($('highlight'))$('highlight').innerHTML='<div class="alert"><b>Não foi possível carregar data.json.</b><p>Recarregue a página.</p></div>'}}
function csvImport(f){const rd=new FileReader();rd.onload=()=>{let text=String(rd.result||'').replace(/^\uFEFF/,'');const lines=text.split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return;let sep=lines.some(x=>x.includes(';'))?';':',';let hi=lines.findIndex(x=>norm(x).includes('promotor de marketing')&&norm(x).includes('valor vendido'));if(hi<0)hi=lines.findIndex(x=>norm(x).includes('promotor'));if(hi<0)hi=0;const h=lines[hi].split(sep).map(x=>x.replace(/^"|"$/g,''));const imported=lines.slice(hi+1).map(line=>{const c=line.split(sep);const o={};h.forEach((k,i)=>o[k]=(c[i]??'').replace(/^"|"$/g,''));return prep(o)}).filter(r=>r.promotor||r.vgv||r.date||r.local);if(!imported.length){alert('Nenhum registro válido encontrado. Os dados atuais foram preservados.');return}rows=imported;filters();render();alert(`Importação concluída: ${num(rows.length)} registros.`)};rd.readAsText(f,'windows-1252')}
function bind(){document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){e.preventDefault();nav(p.dataset.page);return}const r=e.target.closest('[data-rank]');if(r){e.preventDefault();qs('[data-rank]').forEach(x=>x.classList.toggle('active',x===r));return}});['start','end','promotor','liner','closer','local'].forEach(id=>$(id)?.addEventListener('change',render));$('reset')?.addEventListener('click',()=>{filters();render()});$('importBtn')?.addEventListener('click',()=>$('file')?.click());$('file')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)csvImport(f)});$('export')?.addEventListener('click',()=>{const a=filtered(),csv=['PROMOTOR,VGV,VENDAS,CONVERSAO,ATENDIMENTOS',...Object.entries(a.reduce((m,r)=>{const k=r.promotor||'Não informado';(m[k]??=[]).push(r);return m},{})).map(([n,x])=>`"${n.replaceAll('"','""')}",${agg(x).v},${agg(x).sales},${(agg(x).conv*100).toFixed(2)},${agg(x).atend}`)].join('\n'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),ael=document.createElement('a');ael.href=u;ael.download='fluxohub-export.csv';ael.click();URL.revokeObjectURL(u)});$('installPWA')?.addEventListener('click',async()=>{if(window.__fluxoInstallPrompt){window.__fluxoInstallPrompt.prompt();await window.__fluxoInstallPrompt.userChoice;window.__fluxoInstallPrompt=null}else alert('O navegador só mostra a instalação quando o PWA estiver elegível. Use o menu do navegador → Instalar FluxoHub.');});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.__fluxoInstallPrompt=e});}
function start(){bind();load()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();