(function(){
'use strict';
const KEY='captaup_captain_date_v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function iso(d){return d.toISOString().slice(0,10)}
function weekOf(value){const d=new Date(value+'T12:00:00');const day=d.getDay();const diff=(day+6)%7;const mon=new Date(d);mon.setDate(d.getDate()-diff);const sun=new Date(mon);sun.setDate(mon.getDate()+6);return[iso(mon),iso(sun)]}
function br(v){if(!v)return'';const[a,b,c]=v.split('-');return`${c}/${b}/${a}`}
function addStyle(){if($('captain-css'))return;const s=document.createElement('style');s.id='captain-css';s.textContent=`
#captainCard{margin:14px 0;border:1px solid #1f6f4d;border-radius:20px;background:linear-gradient(145deg,#06130f,#071b17 54%,#07111a);box-shadow:0 18px 50px #0008,inset 0 0 45px #20d47b0d;padding:18px}.cap-head{display:flex;gap:14px;align-items:flex-end;justify-content:space-between;flex-wrap:wrap}.cap-eyebrow{font-size:9px;letter-spacing:2px;color:#62e5a1;font-weight:900}.cap-title{font-size:20px;font-weight:950;margin-top:4px}.cap-sub{font-size:10px;color:#8eaaa1;margin-top:4px}.cap-date label{display:block;font-size:9px;color:#8eaaa1;margin-bottom:5px}.cap-date input{background:#08131a;border:1px solid #27483d;color:#eafff4;border-radius:10px;padding:10px 12px}.cap-range{margin-top:12px;padding:9px 11px;border-radius:10px;background:#0b1a17;color:#a8c6ba;font-size:10px}.cap-list{margin-top:14px;display:grid;gap:8px}.cap-row{display:grid;grid-template-columns:38px minmax(0,1fr) auto auto;gap:10px;align-items:center;padding:10px 12px;border-radius:12px;background:#09131a;border:1px solid #182f28}.cap-pos{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#102433;color:#b9dcf2;font-weight:950}.cap-row.winner{border-color:#24dd7f;background:linear-gradient(90deg,#0c2319,#09161a);box-shadow:0 0 28px #1fdc7721}.cap-row.winner .cap-pos{background:#24dd7f;color:#032110;box-shadow:0 0 18px #24dd7f}.cap-name{font-size:11px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cap-meta{font-size:9px;color:#89a79c}.cap-kpi{text-align:right}.cap-kpi b{display:block;font-size:12px;color:#effff6}.cap-kpi span{font-size:8px;color:#79998d}.cap-badge{font-size:8px;font-weight:950;color:#082315;background:#38e78f;padding:5px 7px;border-radius:999px;white-space:nowrap}.cap-empty{padding:18px;text-align:center;color:#8ea59c;font-size:10px}@media(max-width:560px){#captainCard{padding:14px}.cap-title{font-size:17px}.cap-row{grid-template-columns:34px minmax(0,1fr) auto}.cap-badge{grid-column:2/4;justify-self:start}.cap-meta{display:none}}`;
document.head.appendChild(s)}
function ensureCard(){if($('captainCard'))return $('captainCard');const page=$('page-visao');if(!page)return null;const card=document.createElement('div');card.id='captainCard';card.innerHTML=`<div class="cap-head"><div><div class="cap-eyebrow">CAPTAUP • RANKING SEMANAL</div><div class="cap-title">Capitão / Capitã da Semana</div><div class="cap-sub">Semana oficial: segunda a domingo • critério principal: mais Casais</div></div><div class="cap-date"><label>ESCOLHA UMA DATA DA SEMANA</label><input id="captainDate" type="date"></div></div><div class="cap-range" id="captainRange">Selecione uma data</div><div class="cap-list" id="captainList"><div class="cap-empty">Carregando ranking semanal...</div></div>`;const holo=$('cuHolo');if(holo&&holo.parentNode===page)page.insertBefore(card,holo.nextSibling);else page.prepend(card);$('captainDate').addEventListener('change',applyWeek);return card}
function readTop5(){const rows=[...document.querySelectorAll('#rankingTable tbody tr')].slice(0,5);return rows.map((tr,i)=>({pos:i+1,name:(tr.cells[1]?.textContent||'').trim(),casais:(tr.cells[2]?.textContent||'0').trim(),vgv:(tr.cells[3]?.textContent||'R$ 0,00').trim(),vendas:(tr.cells[4]?.textContent||'0').trim()})).filter(x=>x.name)}
function paint(){const list=$('captainList');if(!list)return;const data=readTop5();if(!data.length){list.innerHTML='<div class="cap-empty">Nenhum resultado para esta semana.</div>';return}list.innerHTML=data.map((p,i)=>`<div class="cap-row ${i===0?'winner':''}"><div class="cap-pos">${p.pos}</div><div><div class="cap-name">${esc(p.name)}</div><div class="cap-meta">${esc(p.vgv)} • ${esc(p.vendas)} vendas</div></div><div class="cap-kpi"><b>${esc(p.casais)}</b><span>CASAIS</span></div>${i===0?'<div class="cap-badge">CAPITÃO / CAPITÃ</div>':''}</div>`).join('')}
function applyWeek(){const input=$('captainDate');if(!input||!input.value)return;localStorage.setItem(KEY,input.value);const[mon,sun]=weekOf(input.value);$('captainRange').textContent=`Semana: ${br(mon)} a ${br(sun)}`;const st=$('start'),en=$('end');if(st&&en){st.value=mon;en.value=sun;st.dispatchEvent(new Event('change',{bubbles:true}));en.dispatchEvent(new Event('change',{bubbles:true}))}const casalBtn=document.querySelector('[data-rank="casais"]');if(casalBtn)casalBtn.click();setTimeout(paint,120)}
function restore(){const input=$('captainDate');if(!input)return;const saved=localStorage.getItem(KEY);const fallback=$('end')?.value||'2026-08-22';input.value=saved||fallback;applyWeek()}
function mount(){addStyle();ensureCard();let tries=0;const timer=setInterval(()=>{tries++;ensureCard();const ready=document.querySelector('#rankingTable tbody tr')&&$('start')?.value;if(ready){clearInterval(timer);restore();const target=$('rankingTable');if(target)new MutationObserver(()=>setTimeout(paint,20)).observe(target,{childList:true,subtree:true});['promotor','liner','closer','local'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(paint,80)))}else if(tries>40)clearInterval(timer)},200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();